/**
 * Automotive Category Attribute Mappings
 * 
 * Comprehensive mappings for auto parts, accessories, and maintenance products
 */

export const automotiveMappings = {
  // Main Automotive
  'automotive': ['brand', 'compatibility', 'material', 'color', 'warranty'],
  'auto-parts': ['brand', 'compatibility', 'oem-aftermarket', 'warranty'],
  'car-accessories': ['brand', 'compatibility', 'color', 'material'],
  
  // Engine Parts
  'engine-parts': ['brand', 'compatibility', 'oem-aftermarket', 'material'],
  'air-filters': ['brand', 'compatibility', 'type', 'reusable', 'filtration'],
  'oil-filters': ['brand', 'compatibility', 'thread-size', 'micron-rating'],
  'fuel-filters': ['brand', 'compatibility', 'type', 'micron-rating'],
  'spark-plugs': ['brand', 'compatibility', 'gap', 'heat-range', 'electrode-type'],
  'ignition-coils': ['brand', 'compatibility', 'type', 'warranty'],
  'timing-belts': ['brand', 'compatibility', 'length', 'teeth', 'width'],
  'timing-chains': ['brand', 'compatibility', 'links', 'pitch'],
  'water-pumps': ['brand', 'compatibility', 'material', 'gasket-included'],
  'thermostats': ['brand', 'compatibility', 'temperature-rating', 'gasket-included'],
  'radiators': ['brand', 'compatibility', 'core-size', 'material', 'rows'],
  'radiator-hoses': ['brand', 'compatibility', 'diameter', 'length', 'material'],
  'belts': ['brand', 'compatibility', 'length', 'width', 'type'],
  'serpentine-belts': ['brand', 'compatibility', 'length', 'ribs'],
  'alternators': ['brand', 'compatibility', 'amperage', 'voltage', 'pulley-type'],
  'starters': ['brand', 'compatibility', 'voltage', 'teeth', 'rotation'],
  'batteries': ['brand', 'group-size', 'cca', 'voltage', 'warranty', 'terminal-type'],
  'battery-cables': ['brand', 'compatibility', 'length', 'gauge', 'terminal-type'],
  'engine-mounts': ['brand', 'compatibility', 'position', 'material', 'hydraulic'],
  'gaskets': ['brand', 'compatibility', 'type', 'material', 'thickness'],
  'head-gaskets': ['brand', 'compatibility', 'material', 'thickness', 'bore'],
  'intake-manifolds': ['brand', 'compatibility', 'material', 'gasket-included'],
  'exhaust-manifolds': ['brand', 'compatibility', 'material', 'gasket-included'],
  'turbochargers': ['brand', 'compatibility', 'boost-pressure', 'ar-ratio', 'oil-cooled'],
  'superchargers': ['brand', 'compatibility', 'boost-pressure', 'type', 'drive-type'],
  'intercoolers': ['brand', 'compatibility', 'core-size', 'inlet-outlet', 'material'],
  
  // Transmission & Drivetrain
  'transmission-parts': ['brand', 'compatibility', 'type', 'warranty'],
  'clutches': ['brand', 'compatibility', 'diameter', 'type', 'organic-ceramic'],
  'clutch-kits': ['brand', 'compatibility', 'pieces', 'type'],
  'flywheels': ['brand', 'compatibility', 'weight', 'material', 'teeth'],
  'transmission-filters': ['brand', 'compatibility', 'type', 'micron-rating'],
  'transmission-fluid': ['brand', 'type', 'viscosity', 'volume', 'synthetic'],
  'cv-axles': ['brand', 'compatibility', 'side', 'length', 'abs-sensor'],
  'driveshafts': ['brand', 'compatibility', 'length', 'diameter', 'material'],
  'u-joints': ['brand', 'compatibility', 'size', 'greasable', 'snap-ring'],
  'differentials': ['brand', 'compatibility', 'ratio', 'type', 'limited-slip'],
  'transfer-cases': ['brand', 'compatibility', 'ratio', 'type'],
  
  // Brakes
  'brake-parts': ['brand', 'compatibility', 'position', 'material'],
  'brake-pads': ['brand', 'compatibility', 'position', 'material', 'noise-dampening'],
  'brake-rotors': ['brand', 'compatibility', 'position', 'diameter', 'vented', 'drilled-slotted'],
  'brake-drums': ['brand', 'compatibility', 'position', 'diameter'],
  'brake-shoes': ['brand', 'compatibility', 'position', 'material'],
  'brake-calipers': ['brand', 'compatibility', 'position', 'pistons', 'loaded-unloaded'],
  'brake-lines': ['brand', 'compatibility', 'length', 'material', 'braided'],
  'brake-hoses': ['brand', 'compatibility', 'position', 'length', 'material'],
  'brake-fluid': ['brand', 'dot-rating', 'volume', 'dry-boiling-point'],
  'master-cylinders': ['brand', 'compatibility', 'bore-size', 'reservoir-included'],
  'brake-boosters': ['brand', 'compatibility', 'diameter', 'type'],
  'parking-brake-cables': ['brand', 'compatibility', 'position', 'length'],
  'abs-sensors': ['brand', 'compatibility', 'position', 'wire-length'],
  
  // Suspension & Steering
  'suspension-parts': ['brand', 'compatibility', 'position', 'type'],
  'shocks': ['brand', 'compatibility', 'position', 'type', 'adjustable', 'gas-oil'],
  'struts': ['brand', 'compatibility', 'position', 'type', 'loaded-bare'],
  'coilovers': ['brand', 'compatibility', 'adjustable-height', 'adjustable-damping', 'spring-rate'],
  'springs': ['brand', 'compatibility', 'position', 'rate', 'lowering-lift'],
  'control-arms': ['brand', 'compatibility', 'position', 'upper-lower', 'bushings-included'],
  'ball-joints': ['brand', 'compatibility', 'position', 'upper-lower', 'greasable'],
  'tie-rods': ['brand', 'compatibility', 'position', 'inner-outer', 'adjustable'],
  'sway-bars': ['brand', 'compatibility', 'diameter', 'adjustable', 'bushings-included'],
  'sway-bar-links': ['brand', 'compatibility', 'position', 'length', 'adjustable'],
  'bushings': ['brand', 'compatibility', 'position', 'material', 'polyurethane-rubber'],
  'wheel-bearings': ['brand', 'compatibility', 'position', 'abs-sensor', 'hub-assembly'],
  'steering-racks': ['brand', 'compatibility', 'type', 'power-manual'],
  'power-steering-pumps': ['brand', 'compatibility', 'type', 'reservoir-included'],
  'steering-columns': ['brand', 'compatibility', 'tilt', 'telescoping'],
  'steering-wheels': ['brand', 'diameter', 'material', 'grip-type', 'horn-button'],
  
  // Wheels & Tires
  'wheels-tires': ['brand', 'size', 'type', 'season'],
  'tires': ['brand', 'size', 'load-index', 'speed-rating', 'season', 'tread-pattern'],
  'all-season-tires': ['brand', 'size', 'load-index', 'speed-rating', 'warranty'],
  'summer-tires': ['brand', 'size', 'load-index', 'speed-rating', 'performance-level'],
  'winter-tires': ['brand', 'size', 'load-index', 'speed-rating', 'studded'],
  'performance-tires': ['brand', 'size', 'load-index', 'speed-rating', 'treadwear'],
  'off-road-tires': ['brand', 'size', 'load-index', 'terrain', 'ply-rating'],
  'wheels': ['brand', 'diameter', 'width', 'bolt-pattern', 'offset', 'material', 'finish'],
  'alloy-wheels': ['brand', 'diameter', 'width', 'bolt-pattern', 'offset', 'finish'],
  'steel-wheels': ['brand', 'diameter', 'width', 'bolt-pattern', 'offset', 'finish'],
  'wheel-spacers': ['brand', 'thickness', 'bolt-pattern', 'hub-centric', 'material'],
  'lug-nuts': ['brand', 'thread-size', 'seat-type', 'finish', 'quantity'],
  'wheel-locks': ['brand', 'thread-size', 'seat-type', 'finish', 'key-pattern'],
  'tire-pressure-sensors': ['brand', 'compatibility', 'frequency', 'programmable'],
  'valve-stems': ['brand', 'type', 'length', 'material', 'tpms-compatible'],
  
  // Exhaust System
  'exhaust-parts': ['brand', 'compatibility', 'material', 'diameter'],
  'mufflers': ['brand', 'compatibility', 'material', 'inlet-outlet', 'sound-level'],
  'catalytic-converters': ['brand', 'compatibility', 'epa-approved', 'carb-compliant'],
  'exhaust-pipes': ['brand', 'compatibility', 'diameter', 'material', 'length'],
  'headers': ['brand', 'compatibility', 'material', 'coating', 'primary-diameter'],
  'downpipes': ['brand', 'compatibility', 'diameter', 'catted-catless', 'material'],
  'exhaust-tips': ['brand', 'diameter', 'length', 'material', 'finish', 'angle'],
  'exhaust-hangers': ['brand', 'compatibility', 'material', 'type'],
  'exhaust-gaskets': ['brand', 'compatibility', 'diameter', 'material'],
  'resonators': ['brand', 'diameter', 'length', 'material', 'inlet-outlet'],
  
  // Fuel System
  'fuel-system': ['brand', 'compatibility', 'type', 'material'],
  'fuel-pumps': ['brand', 'compatibility', 'flow-rate', 'pressure', 'in-tank-inline'],
  'fuel-injectors': ['brand', 'compatibility', 'flow-rate', 'impedance', 'connector-type'],
  'fuel-pressure-regulators': ['brand', 'compatibility', 'pressure-range', 'adjustable'],
  'fuel-rails': ['brand', 'compatibility', 'material', 'finish', 'fittings-included'],
  'fuel-lines': ['brand', 'compatibility', 'diameter', 'material', 'length'],
  'fuel-caps': ['brand', 'compatibility', 'vented', 'locking'],
  'fuel-tanks': ['brand', 'compatibility', 'capacity', 'material', 'pump-included'],
  
  // Cooling System
  'cooling-system': ['brand', 'compatibility', 'material', 'capacity'],
  'coolant': ['brand', 'type', 'color', 'volume', 'pre-mixed', 'temperature-range'],
  'radiator-caps': ['brand', 'compatibility', 'pressure-rating', 'lever-type'],
  'cooling-fans': ['brand', 'compatibility', 'diameter', 'cfm', 'push-pull'],
  'fan-clutches': ['brand', 'compatibility', 'type', 'thermal-non-thermal'],
  'expansion-tanks': ['brand', 'compatibility', 'capacity', 'material', 'cap-included'],
  
  // Electrical
  'electrical-parts': ['brand', 'compatibility', 'voltage', 'amperage'],
  'headlights': ['brand', 'compatibility', 'side', 'bulb-type', 'housing-type'],
  'tail-lights': ['brand', 'compatibility', 'side', 'led-halogen', 'smoked-clear'],
  'fog-lights': ['brand', 'compatibility', 'bulb-type', 'mounting', 'color-temperature'],
  'light-bulbs': ['brand', 'bulb-type', 'wattage', 'color-temperature', 'quantity'],
  'led-bulbs': ['brand', 'bulb-type', 'lumens', 'color-temperature', 'canbus'],
  'hid-kits': ['brand', 'bulb-type', 'color-temperature', 'wattage', 'ballast-included'],
  'light-bars': ['brand', 'length', 'lumens', 'beam-pattern', 'mounting'],
  'switches': ['brand', 'compatibility', 'type', 'illuminated', 'momentary-latching'],
  'relays': ['brand', 'pins', 'voltage', 'amperage', 'type'],
  'fuses': ['brand', 'amperage', 'type', 'quantity'],
  'fuse-boxes': ['brand', 'compatibility', 'circuits', 'blade-type'],
  'wiring-harnesses': ['brand', 'compatibility', 'purpose', 'length'],
  'battery-chargers': ['brand', 'amperage', 'voltage', 'automatic', 'jump-start'],
  'jump-starters': ['brand', 'peak-amps', 'battery-capacity', 'usb-ports', 'compressor'],
  'inverters': ['brand', 'wattage', 'input-voltage', 'outlets', 'usb-ports'],
  
  // Interior Accessories
  'interior-accessories': ['brand', 'compatibility', 'color', 'material'],
  'floor-mats': ['brand', 'compatibility', 'material', 'color', 'pieces', 'all-weather'],
  'seat-covers': ['brand', 'compatibility', 'material', 'color', 'rows', 'heated-compatible'],
  'steering-wheel-covers': ['brand', 'diameter', 'material', 'color', 'grip-type'],
  'shift-knobs': ['brand', 'thread-size', 'material', 'color', 'weighted'],
  'pedal-covers': ['brand', 'material', 'color', 'pieces', 'automatic-manual'],
  'sun-shades': ['brand', 'size', 'material', 'foldable', 'reflective'],
  'car-organizers': ['brand', 'type', 'material', 'compartments', 'mounting'],
  'cup-holders': ['brand', 'diameter', 'adjustable', 'mounting-type'],
  'phone-mounts': ['brand', 'mounting-type', 'adjustable', 'wireless-charging', 'compatibility'],
  'dash-cams': ['brand', 'resolution', 'viewing-angle', 'night-vision', 'gps', 'parking-mode'],
  'backup-cameras': ['brand', 'resolution', 'viewing-angle', 'night-vision', 'waterproof'],
  'car-stereos': ['brand', 'din-size', 'touchscreen', 'bluetooth', 'apple-carplay', 'android-auto'],
  'speakers': ['brand', 'size', 'power', 'impedance', 'component-coaxial'],
  'subwoofers': ['brand', 'size', 'power', 'impedance', 'voice-coils'],
  'amplifiers': ['brand', 'channels', 'power', 'class', 'bridgeable'],
  'air-fresheners': ['brand', 'scent', 'type', 'duration'],
  
  // Exterior Accessories
  'exterior-accessories': ['brand', 'compatibility', 'color', 'material'],
  'car-covers': ['brand', 'compatibility', 'material', 'waterproof', 'layers', 'indoor-outdoor'],
  'windshield-wipers': ['brand', 'length', 'type', 'connector', 'beam-conventional'],
  'wiper-blades': ['brand', 'length', 'type', 'connector', 'all-season'],
  'mirrors': ['brand', 'compatibility', 'side', 'power', 'heated', 'signal'],
  'door-handles': ['brand', 'compatibility', 'side', 'color', 'keyless-entry'],
  'grilles': ['brand', 'compatibility', 'material', 'finish', 'mesh-billet'],
  'bumpers': ['brand', 'compatibility', 'position', 'material', 'finish', 'fog-light-holes'],
  'fenders': ['brand', 'compatibility', 'side', 'material', 'finish'],
  'hoods': ['brand', 'compatibility', 'material', 'finish', 'scoop', 'vented'],
  'spoilers': ['brand', 'compatibility', 'material', 'finish', 'adjustable'],
  'body-kits': ['brand', 'compatibility', 'pieces', 'material', 'finish'],
  'mud-flaps': ['brand', 'compatibility', 'material', 'logo', 'hardware-included'],
  'running-boards': ['brand', 'compatibility', 'material', 'finish', 'length', 'lighted'],
  'nerf-bars': ['brand', 'compatibility', 'material', 'finish', 'diameter', 'steps'],
  'tonneau-covers': ['brand', 'compatibility', 'type', 'material', 'locking', 'folding-rolling'],
  'bed-liners': ['brand', 'compatibility', 'material', 'drop-in-spray', 'tailgate-protection'],
  'hitches': ['brand', 'compatibility', 'class', 'weight-capacity', 'receiver-size'],
  'hitch-balls': ['brand', 'diameter', 'shank-diameter', 'weight-capacity', 'finish'],
  'bike-racks': ['brand', 'capacity', 'mounting-type', 'bikes', 'tilt', 'locking'],
  'cargo-carriers': ['brand', 'capacity', 'size', 'mounting-type', 'waterproof'],
  'roof-racks': ['brand', 'compatibility', 'weight-capacity', 'crossbars', 'aerodynamic'],
  'window-visors': ['brand', 'compatibility', 'pieces', 'material', 'in-channel-stick-on'],
  'emblems': ['brand', 'compatibility', 'type', 'finish', 'adhesive-clip'],
  'decals': ['size', 'color', 'material', 'weather-resistant', 'removable'],
  'license-plate-frames': ['brand', 'material', 'finish', 'logo', 'screw-caps'],
  
  // Maintenance & Fluids
  'maintenance-fluids': ['brand', 'type', 'volume', 'viscosity'],
  'motor-oil': ['brand', 'viscosity', 'volume', 'synthetic', 'api-rating', 'diesel-gas'],
  'transmission-oil': ['brand', 'type', 'volume', 'viscosity', 'synthetic'],
  'gear-oil': ['brand', 'viscosity', 'volume', 'synthetic', 'limited-slip'],
  'power-steering-fluid': ['brand', 'type', 'volume', 'compatibility'],
  'windshield-washer-fluid': ['brand', 'volume', 'temperature-rating', 'bug-remover'],
  'antifreeze': ['brand', 'type', 'volume', 'color', 'pre-mixed', 'temperature-rating'],
  'grease': ['brand', 'type', 'volume', 'temperature-range', 'lithium-synthetic'],
  'additives': ['brand', 'type', 'volume', 'purpose', 'fuel-oil'],
  'fuel-additives': ['brand', 'type', 'volume', 'purpose', 'octane-boost'],
  'oil-additives': ['brand', 'type', 'volume', 'purpose', 'stop-leak'],
  
  // Tools & Equipment
  'auto-tools': ['brand', 'type', 'size', 'material'],
  'jack-stands': ['brand', 'capacity', 'height-range', 'pair', 'locking-mechanism'],
  'floor-jacks': ['brand', 'capacity', 'lift-range', 'type', 'wheels'],
  'ramps': ['brand', 'capacity', 'height', 'length', 'material', 'pair'],
  'creepers': ['brand', 'weight-capacity', 'wheels', 'padded', 'headrest'],
  'oil-drain-pans': ['brand', 'capacity', 'material', 'spout', 'screen'],
  'funnels': ['brand', 'diameter', 'material', 'filter', 'flexible'],
  'socket-sets': ['brand', 'pieces', 'drive-size', 'metric-sae', 'case'],
  'wrench-sets': ['brand', 'pieces', 'type', 'metric-sae', 'finish'],
  'screwdriver-sets': ['brand', 'pieces', 'types', 'magnetic', 'case'],
  'pliers-sets': ['brand', 'pieces', 'types', 'material', 'case'],
  'torque-wrenches': ['brand', 'drive-size', 'range', 'accuracy', 'type'],
  'impact-wrenches': ['brand', 'drive-size', 'torque', 'power-source', 'speed-settings'],
  'air-compressors': ['brand', 'tank-size', 'psi', 'cfm', 'power-source', 'portable'],
  'pressure-washers': ['brand', 'psi', 'gpm', 'power-source', 'hose-length'],
  'multimeters': ['brand', 'type', 'voltage-range', 'auto-ranging', 'display'],
  'scan-tools': ['brand', 'compatibility', 'functions', 'display', 'wireless'],
  'code-readers': ['brand', 'compatibility', 'display', 'live-data', 'wireless'],
  
  // Cleaning & Detailing
  'car-care': ['brand', 'type', 'volume', 'purpose'],
  'car-wash-soap': ['brand', 'volume', 'ph-balanced', 'wax-included', 'concentrate'],
  'car-wax': ['brand', 'volume', 'type', 'carnauba-synthetic', 'application'],
  'polish': ['brand', 'volume', 'type', 'abrasive-level', 'application'],
  'clay-bars': ['brand', 'weight', 'grade', 'lubricant-included'],
  'tire-shine': ['brand', 'volume', 'finish', 'water-based', 'spray-gel'],
  'wheel-cleaner': ['brand', 'volume', 'acid-free', 'spray-foam'],
  'glass-cleaner': ['brand', 'volume', 'ammonia-free', 'streak-free'],
  'interior-cleaner': ['brand', 'volume', 'surface-type', 'spray-foam'],
  'leather-cleaner': ['brand', 'volume', 'conditioner-included', 'ph-balanced'],
  'leather-conditioner': ['brand', 'volume', 'uv-protection', 'application'],
  'upholstery-cleaner': ['brand', 'volume', 'stain-type', 'spray-foam'],
  'engine-degreaser': ['brand', 'volume', 'biodegradable', 'spray-concentrate'],
  'bug-tar-remover': ['brand', 'volume', 'spray-gel', 'safe-for-paint'],
  'scratch-remover': ['brand', 'volume', 'scratch-depth', 'application'],
  'compound': ['brand', 'volume', 'cut-level', 'application'],
  'microfiber-towels': ['brand', 'size', 'gsm', 'quantity', 'color', 'edgeless'],
  'wash-mitts': ['brand', 'material', 'size', 'scratch-free'],
  'brushes': ['brand', 'type', 'bristle-type', 'size', 'purpose'],
  'foam-cannons': ['brand', 'capacity', 'connector-type', 'adjustable'],
  'pressure-washer-attachments': ['brand', 'type', 'connector', 'material'],
  'vacuum-cleaners': ['brand', 'type', 'power', 'capacity', 'wet-dry', 'attachments'],
  
  // Performance Parts
  'performance-parts': ['brand', 'compatibility', 'material', 'power-gain'],
  'cold-air-intakes': ['brand', 'compatibility', 'material', 'filter-type', 'power-gain'],
  'exhaust-systems': ['brand', 'compatibility', 'material', 'cat-back-axle-back', 'sound-level'],
  'performance-chips': ['brand', 'compatibility', 'power-gain', 'programmable'],
  'tuners': ['brand', 'compatibility', 'preloaded-tunes', 'custom-tuning', 'display'],
  'blow-off-valves': ['brand', 'compatibility', 'type', 'sound', 'adjustable'],
  'wastegates': ['brand', 'compatibility', 'spring-pressure', 'internal-external'],
  'fuel-management': ['brand', 'compatibility', 'type', 'injector-support'],
  'nitrous-kits': ['brand', 'compatibility', 'horsepower', 'wet-dry', 'bottle-size'],
  'gauges': ['brand', 'type', 'size', 'digital-analog', 'color', 'warning'],
  'gauge-pods': ['brand', 'compatibility', 'gauges', 'mounting-location'],
  
  // Off-Road & 4x4
  'off-road-parts': ['brand', 'compatibility', 'material', 'finish'],
  'lift-kits': ['brand', 'compatibility', 'lift-height', 'type', 'components'],
  'leveling-kits': ['brand', 'compatibility', 'lift-height', 'front-rear'],
  'skid-plates': ['brand', 'compatibility', 'material', 'thickness', 'coverage'],
  'rock-sliders': ['brand', 'compatibility', 'material', 'finish', 'step'],
  'winches': ['brand', 'pull-rating', 'rope-type', 'motor-type', 'wireless-remote'],
  'winch-accessories': ['brand', 'type', 'rating', 'material'],
  'recovery-straps': ['brand', 'length', 'capacity', 'material', 'loops'],
  'shackles': ['brand', 'capacity', 'type', 'material', 'pin-diameter'],
  'air-lockers': ['brand', 'compatibility', 'type', 'compressor-included'],
  'snorkels': ['brand', 'compatibility', 'material', 'side', 'raised-air-ram'],
  'fender-flares': ['brand', 'compatibility', 'material', 'finish', 'coverage'],
  'bumpers-off-road': ['brand', 'compatibility', 'position', 'material', 'winch-mount', 'd-rings'],
  'light-mounts': ['brand', 'compatibility', 'light-size', 'mounting-location'],
  
  // Towing & Hauling
  'towing-hauling': ['brand', 'compatibility', 'capacity', 'class'],
  'trailer-hitches': ['brand', 'compatibility', 'class', 'weight-capacity', 'receiver-size'],
  'fifth-wheel-hitches': ['brand', 'weight-capacity', 'jaw-size', 'slider'],
  'gooseneck-hitches': ['brand', 'weight-capacity', 'ball-size', 'removable'],
  'weight-distribution': ['brand', 'weight-capacity', 'shank-size', 'sway-control'],
  'trailer-couplers': ['brand', 'ball-size', 'weight-capacity', 'locking'],
  'trailer-jacks': ['brand', 'weight-capacity', 'lift-height', 'type', 'wheel'],
  'trailer-lights': ['brand', 'type', 'led-incandescent', 'mounting', 'waterproof'],
  'wiring-adapters': ['brand', 'connector-type', 'pins', 'length'],
  'brake-controllers': ['brand', 'type', 'axles', 'display', 'proportional-time-delayed'],
  'tow-mirrors': ['brand', 'compatibility', 'power', 'heated', 'signal', 'extending'],
  'trailer-brakes': ['brand', 'size', 'type', 'electric-hydraulic', 'capacity'],
  
  // Safety & Security
  'safety-security': ['brand', 'type', 'compatibility'],
  'car-alarms': ['brand', 'zones', 'remote-range', 'two-way', 'smartphone-app'],
  'gps-trackers': ['brand', 'subscription', 'battery-life', 'real-time', 'geofencing'],
  'steering-wheel-locks': ['brand', 'type', 'material', 'visibility', 'universal'],
  'wheel-locks': ['brand', 'thread-size', 'key-pattern', 'finish', 'quantity'],
  'kill-switches': ['brand', 'type', 'hidden', 'wireless'],
  'fire-extinguishers': ['brand', 'size', 'type', 'mounting-bracket', 'rechargeable'],
  'first-aid-kits': ['brand', 'pieces', 'case-type', 'compact'],
  'emergency-kits': ['brand', 'pieces', 'jumper-cables', 'flashlight', 'case'],
  'reflective-triangles': ['brand', 'quantity', 'foldable', 'weighted', 'case'],
  'child-safety-seats': ['brand', 'age-group', 'weight-range', 'isofix', 'recline-positions'],
  'seat-belt-extenders': ['brand', 'length', 'buckle-type', 'certified'],
};

