export const fashionMappings = {
 // Fashion Category Mappings
 //Includes: Men, Women, Kids, Bags, Accessories
  // Add your fashion category mappings here
  // Example:
  // ==========================================
  // FASHION & CLOTHING
  // ==========================================
  
  // Main Fashion Category
  'fashion': ['size', 'color', 'material', 'brand', 'gender', 'style'],
  'clothing': ['size', 'color', 'material', 'brand', 'gender', 'style', 'fit'],
  
  // Men's Fashion
  'mens-fashion': ['size', 'color', 'material', 'brand', 'fit', 'style'],
  'mens-clothing': ['size', 'color', 'material', 'brand', 'fit', 'style'],
  'mens-shirts': ['size', 'color', 'material', 'brand', 'collar-type', 'sleeve-length', 'fit', 'pattern'],
  'mens-t-shirts': ['size', 'color', 'material', 'brand', 'neck-type', 'sleeve-length', 'fit'],
  'mens-polo-shirts': ['size', 'color', 'material', 'brand', 'fit', 'collar-type'],
  'mens-pants': ['size', 'color', 'material', 'brand', 'fit', 'length', 'waist-size', 'style'],
  'mens-jeans': ['size', 'color', 'brand', 'fit', 'length', 'waist-size', 'wash', 'distressed'],
  'mens-shorts': ['size', 'color', 'material', 'brand', 'fit', 'length', 'style'],
  'mens-suits': ['size', 'color', 'material', 'brand', 'fit', 'pieces', 'style'],
  'mens-jackets': ['size', 'color', 'material', 'brand', 'style', 'season', 'waterproof'],
  'mens-coats': ['size', 'color', 'material', 'brand', 'length', 'season', 'insulation'],
  'mens-sweaters': ['size', 'color', 'material', 'brand', 'neck-type', 'sleeve-length', 'pattern'],
  'mens-hoodies': ['size', 'color', 'material', 'brand', 'style', 'fit', 'zipper'],
  'mens-activewear': ['size', 'color', 'material', 'brand', 'sport-type', 'fit'],
  'mens-underwear': ['size', 'color', 'material', 'brand', 'style', 'pack-size'],
  'mens-socks': ['size', 'color', 'material', 'brand', 'length', 'pack-size'],
  'mens-sleepwear': ['size', 'color', 'material', 'brand', 'style', 'season'],
  
  // Women's Fashion
  'womens-fashion': ['size', 'color', 'material', 'brand', 'fit', 'style'],
  'womens-clothing': ['size', 'color', 'material', 'brand', 'fit', 'style'],
  'womens-dresses': ['size', 'color', 'material', 'brand', 'length', 'style', 'occasion', 'neckline'],
  'womens-tops': ['size', 'color', 'material', 'brand', 'sleeve-length', 'neck-type', 'fit', 'style'],
  'womens-blouses': ['size', 'color', 'material', 'brand', 'sleeve-length', 'neck-type', 'fit'],
  'womens-t-shirts': ['size', 'color', 'material', 'brand', 'neck-type', 'sleeve-length', 'fit'],
  'womens-pants': ['size', 'color', 'material', 'brand', 'fit', 'length', 'style'],
  'womens-jeans': ['size', 'color', 'brand', 'fit', 'length', 'wash', 'rise', 'distressed'],
  'womens-skirts': ['size', 'color', 'material', 'brand', 'length', 'style', 'pattern'],
  'womens-shorts': ['size', 'color', 'material', 'brand', 'fit', 'length', 'style'],
  'womens-jackets': ['size', 'color', 'material', 'brand', 'style', 'season', 'length'],
  'womens-coats': ['size', 'color', 'material', 'brand', 'length', 'season', 'style'],
  'womens-sweaters': ['size', 'color', 'material', 'brand', 'neck-type', 'sleeve-length', 'style'],
  'womens-cardigans': ['size', 'color', 'material', 'brand', 'length', 'closure-type'],
  'womens-hoodies': ['size', 'color', 'material', 'brand', 'style', 'fit', 'zipper'],
  'womens-activewear': ['size', 'color', 'material', 'brand', 'sport-type', 'fit', 'support-level'],
  'womens-lingerie': ['size', 'color', 'material', 'brand', 'style', 'support-level'],
  'womens-underwear': ['size', 'color', 'material', 'brand', 'style', 'pack-size'],
  'womens-sleepwear': ['size', 'color', 'material', 'brand', 'style', 'season', 'pieces'],
  'womens-swimwear': ['size', 'color', 'material', 'brand', 'style', 'coverage', 'support-level'],
  
  // Kids & Baby Fashion
  'kids-fashion': ['size', 'color', 'material', 'brand', 'age-group', 'gender'],
  'kids-clothing': ['size', 'color', 'material', 'brand', 'age-group', 'gender', 'style'],
  'boys-clothing': ['size', 'color', 'material', 'brand', 'age-group', 'style'],
  'boys-shirts': ['size', 'color', 'material', 'brand', 'age-group', 'sleeve-length'],
  'boys-pants': ['size', 'color', 'material', 'brand', 'age-group', 'fit', 'style'],
  'boys-shorts': ['size', 'color', 'material', 'brand', 'age-group', 'length'],
  'boys-outerwear': ['size', 'color', 'material', 'brand', 'age-group', 'season'],
  'girls-clothing': ['size', 'color', 'material', 'brand', 'age-group', 'style'],
  'girls-dresses': ['size', 'color', 'material', 'brand', 'age-group', 'length', 'occasion'],
  'girls-tops': ['size', 'color', 'material', 'brand', 'age-group', 'sleeve-length'],
  'girls-pants': ['size', 'color', 'material', 'brand', 'age-group', 'fit'],
  'girls-skirts': ['size', 'color', 'material', 'brand', 'age-group', 'length'],
  'girls-outerwear': ['size', 'color', 'material', 'brand', 'age-group', 'season'],
  'baby-clothing': ['size', 'color', 'material', 'brand', 'age-group', 'gender', 'closure-type'],
  'baby-bodysuits': ['size', 'color', 'material', 'brand', 'age-group', 'sleeve-length', 'pack-size'],
  'baby-sleepwear': ['size', 'color', 'material', 'brand', 'age-group', 'season', 'safety-certified'],
  
  // Footwear
  'footwear': ['size', 'color', 'material', 'brand', 'gender', 'style'],
  'shoes': ['size', 'color', 'material', 'brand', 'gender', 'style', 'closure-type'],
  'mens-shoes': ['size', 'color', 'material', 'brand', 'style', 'width', 'closure-type'],
  'mens-sneakers': ['size', 'color', 'material', 'brand', 'style', 'sport-type'],
  'mens-formal-shoes': ['size', 'color', 'material', 'brand', 'style', 'toe-type'],
  'mens-boots': ['size', 'color', 'material', 'brand', 'height', 'style', 'waterproof'],
  'mens-sandals': ['size', 'color', 'material', 'brand', 'style', 'closure-type'],
  'mens-slippers': ['size', 'color', 'material', 'brand', 'style', 'indoor-outdoor'],
  'womens-shoes': ['size', 'color', 'material', 'brand', 'style', 'heel-height', 'width'],
  'womens-heels': ['size', 'color', 'material', 'brand', 'heel-height', 'heel-type', 'style'],
  'womens-flats': ['size', 'color', 'material', 'brand', 'style', 'toe-type'],
  'womens-sneakers': ['size', 'color', 'material', 'brand', 'style', 'sport-type'],
  'womens-boots': ['size', 'color', 'material', 'brand', 'height', 'heel-height', 'style'],
  'womens-sandals': ['size', 'color', 'material', 'brand', 'heel-height', 'style'],
  'womens-slippers': ['size', 'color', 'material', 'brand', 'style', 'indoor-outdoor'],
  'kids-shoes': ['size', 'color', 'material', 'brand', 'age-group', 'gender', 'closure-type'],
  'boys-shoes': ['size', 'color', 'material', 'brand', 'age-group', 'style', 'closure-type'],
  'girls-shoes': ['size', 'color', 'material', 'brand', 'age-group', 'style', 'closure-type'],
  'baby-shoes': ['size', 'color', 'material', 'brand', 'age-group', 'soft-sole'],
  
  // Bags & Luggage
  'bags': ['color', 'material', 'brand', 'size', 'style', 'capacity', 'gender'],
  'handbags': ['color', 'material', 'brand', 'size', 'style', 'closure-type', 'strap-type'],
  'shoulder-bags': ['color', 'material', 'brand', 'size', 'style', 'strap-adjustable'],
  'crossbody-bags': ['color', 'material', 'brand', 'size', 'style', 'strap-length'],
  'tote-bags': ['color', 'material', 'brand', 'size', 'closure-type', 'pockets'],
  'clutches': ['color', 'material', 'brand', 'size', 'style', 'occasion'],
  'backpacks': ['color', 'material', 'brand', 'size', 'capacity', 'laptop-compartment', 'waterproof'],
  'school-backpacks': ['color', 'material', 'brand', 'size', 'age-group', 'compartments'],
  'travel-backpacks': ['color', 'material', 'brand', 'capacity', 'waterproof', 'laptop-size'],
  'messenger-bags': ['color', 'material', 'brand', 'size', 'laptop-size', 'compartments'],
  'briefcases': ['color', 'material', 'brand', 'size', 'laptop-size', 'lock'],
  'luggage': ['color', 'material', 'brand', 'size', 'wheels', 'expandable', 'lock'],
  'suitcases': ['color', 'material', 'brand', 'size', 'wheels', 'hard-soft', 'expandable'],
  'carry-on-luggage': ['color', 'material', 'brand', 'wheels', 'capacity', 'airline-approved'],
  'duffel-bags': ['color', 'material', 'brand', 'size', 'capacity', 'wheels'],
  'wallets': ['color', 'material', 'brand', 'size', 'gender', 'card-slots', 'coin-pocket'],
  'purses': ['color', 'material', 'brand', 'size', 'closure-type', 'card-slots'],
  
  // Accessories
  'accessories': ['color', 'material', 'brand', 'size', 'gender', 'style'],
  'jewelry': ['material', 'color', 'brand', 'size', 'stone-type', 'plating', 'style'],
  'necklaces': ['material', 'color', 'brand', 'length', 'stone-type', 'style'],
  'earrings': ['material', 'color', 'brand', 'stone-type', 'closure-type', 'style'],
  'bracelets': ['material', 'color', 'brand', 'size', 'stone-type', 'adjustable'],
  'rings': ['material', 'color', 'brand', 'size', 'stone-type', 'style'],
  'watches': ['brand', 'color', 'material', 'gender', 'movement-type', 'water-resistance', 'strap-material'],
  'mens-watches': ['brand', 'color', 'material', 'movement-type', 'water-resistance', 'dial-color'],
  'womens-watches': ['brand', 'color', 'material', 'movement-type', 'water-resistance', 'style'],
  'belts': ['size', 'color', 'material', 'brand', 'gender', 'buckle-type', 'width'],
  'mens-belts': ['size', 'color', 'material', 'brand', 'buckle-type', 'width', 'reversible'],
  'womens-belts': ['size', 'color', 'material', 'brand', 'buckle-type', 'width', 'style'],
  'hats': ['size', 'color', 'material', 'brand', 'gender', 'style', 'season'],
  'caps': ['size', 'color', 'material', 'brand', 'style', 'adjustable'],
  'beanies': ['color', 'material', 'brand', 'style', 'season'],
  'scarves': ['color', 'material', 'brand', 'size', 'pattern', 'season', 'gender'],
  'gloves': ['size', 'color', 'material', 'brand', 'gender', 'season', 'touchscreen'],
  'sunglasses': ['color', 'material', 'brand', 'gender', 'lens-type', 'uv-protection', 'polarized'],
  'eyeglasses': ['color', 'material', 'brand', 'gender', 'frame-shape', 'lens-type'],
  'ties': ['color', 'material', 'brand', 'width', 'pattern', 'length'],
  'bow-ties': ['color', 'material', 'brand', 'style', 'pre-tied'],
  'pocket-squares': ['color', 'material', 'brand', 'size', 'pattern'],
  'hair-accessories': ['color', 'material', 'brand', 'type', 'age-group'],
  
};