/**
 * Garden & Outdoor Category Attribute Mappings
 * 
 * Comprehensive mappings for garden, outdoor, and lawn care products
 */

export const gardenOutdoorMappings = {
  // Main Garden & Outdoor
  'garden-outdoor': ['brand', 'size', 'material', 'color', 'weather-resistant'],
  'garden': ['brand', 'size', 'material', 'type', 'season'],
  'outdoor': ['brand', 'size', 'material', 'weather-resistant', 'assembly-required'],
  
  // Lawn Care
  'lawn-care': ['brand', 'size', 'type', 'coverage', 'organic'],
  'lawn-mowers': ['brand', 'type', 'cutting-width', 'power-source', 'self-propelled', 'bag-capacity'],
  'push-mowers': ['brand', 'cutting-width', 'power-source', 'bag-capacity', 'height-adjustments'],
  'riding-mowers': ['brand', 'cutting-width', 'engine-power', 'transmission', 'fuel-capacity'],
  'zero-turn-mowers': ['brand', 'cutting-width', 'engine-power', 'speed', 'fuel-capacity'],
  'robotic-mowers': ['brand', 'cutting-width', 'battery-life', 'coverage-area', 'app-controlled'],
  'reel-mowers': ['brand', 'cutting-width', 'blades', 'height-adjustments', 'grass-catcher'],
  'string-trimmers': ['brand', 'power-source', 'cutting-width', 'shaft-type', 'line-feed'],
  'edgers': ['brand', 'power-source', 'blade-diameter', 'depth-adjustment', 'wheeled'],
  'leaf-blowers': ['brand', 'power-source', 'airspeed', 'cfm', 'vacuum-mode', 'bag-capacity'],
  'leaf-vacuums': ['brand', 'power-source', 'bag-capacity', 'mulch-ratio', 'wheels'],
  'lawn-aerators': ['brand', 'type', 'width', 'spike-plug', 'tow-behind-push'],
  'lawn-rollers': ['brand', 'width', 'capacity', 'material', 'tow-behind-push'],
  'dethatchers': ['brand', 'type', 'width', 'power-source', 'tines'],
  'spreaders': ['brand', 'type', 'capacity', 'coverage', 'broadcast-drop'],
  'sprayers': ['brand', 'capacity', 'type', 'pressure', 'nozzle-adjustable'],

  // Lawn & Garden Products
  'lawn-fertilizer': ['brand', 'weight', 'coverage', 'npk-ratio', 'organic', 'slow-release'],
  'grass-seed': ['brand', 'weight', 'coverage', 'grass-type', 'sun-shade', 'climate'],
  'weed-killer': ['brand', 'size', 'coverage', 'selective-non-selective', 'organic', 'concentrate-ready'],
  'pest-control': ['brand', 'size', 'pest-type', 'organic', 'indoor-outdoor', 'spray-granules'],
  'mulch': ['brand', 'volume', 'material', 'color', 'organic', 'coverage'],
  'soil': ['brand', 'volume', 'type', 'organic', 'ph-level', 'purpose'],
  'compost': ['brand', 'volume', 'organic', 'aged', 'ingredients'],
  'peat-moss': ['brand', 'volume', 'compressed', 'ph-level'],
  'potting-mix': ['brand', 'volume', 'organic', 'moisture-control', 'plant-type'],
  'garden-soil': ['brand', 'volume', 'organic', 'type', 'raised-bed-in-ground'],
  'topsoil': ['brand', 'volume', 'organic', 'screened', 'purpose'],
  'sand': ['brand', 'weight', 'type', 'grain-size', 'purpose'],
  'gravel': ['brand', 'weight', 'size', 'color', 'purpose'],
  'decorative-stone': ['brand', 'weight', 'size', 'color', 'type'],
  'landscape-fabric': ['brand', 'size', 'material', 'weed-barrier', 'water-permeable'],
  'edging': ['brand', 'length', 'material', 'height', 'flexible-rigid'],
  'garden-stakes': ['brand', 'length', 'material', 'diameter', 'quantity'],
  'plant-ties': ['brand', 'length', 'material', 'adjustable', 'quantity'],
  'plant-labels': ['brand', 'quantity', 'material', 'writable', 'weather-resistant'],
  
  // Garden Tools
  'garden-tools': ['brand', 'material', 'handle-length', 'type'],
  'shovels': ['brand', 'type', 'handle-length', 'blade-material', 'handle-material'],
  'spades': ['brand', 'blade-width', 'handle-length', 'material', 'd-handle-straight'],
  'rakes': ['brand', 'type', 'width', 'tines', 'handle-length'],
  'hoes': ['brand', 'type', 'blade-width', 'handle-length', 'material'],
  'cultivators': ['brand', 'type', 'tines', 'handle-length', 'power-manual'],
  'tillers': ['brand', 'type', 'tilling-width', 'power-source', 'tines', 'depth'],
  'pruners': ['brand', 'type', 'blade-length', 'bypass-anvil', 'handle-material'],
  'loppers': ['brand', 'blade-length', 'handle-length', 'bypass-anvil', 'gear-ratchet'],
  'hedge-shears': ['brand', 'blade-length', 'power-manual', 'handle-length', 'wavy-straight'],
  'pruning-saws': ['brand', 'blade-length', 'teeth-per-inch', 'folding', 'curved-straight'],
  'pole-saws': ['brand', 'reach', 'power-manual', 'extendable', 'blade-length'],
  'chainsaws': ['brand', 'bar-length', 'power-source', 'engine-size', 'chain-speed'],
  'axes': ['brand', 'head-weight', 'handle-length', 'handle-material', 'splitting-felling'],
  'garden-forks': ['brand', 'tines', 'handle-length', 'material', 'd-handle-straight'],
  'trowels': ['brand', 'blade-width', 'handle-length', 'material', 'ergonomic'],
  'hand-cultivators': ['brand', 'tines', 'handle-length', 'material'],
  'weeders': ['brand', 'type', 'handle-length', 'material', 'stand-up-handheld'],
  'garden-knives': ['brand', 'blade-length', 'blade-material', 'folding', 'serrated'],
  'dibbers': ['brand', 'length', 'material', 'depth-markings'],
  'bulb-planters': ['brand', 'type', 'depth', 'diameter', 'handle-length'],
  'wheelbarrows': ['brand', 'capacity', 'wheels', 'material', 'tray-type'],
  'garden-carts': ['brand', 'capacity', 'wheels', 'material', 'dump-feature'],
  'kneelers': ['brand', 'weight-capacity', 'handles', 'cushion-thickness', 'foldable'],
  'garden-stools': ['brand', 'height', 'weight-capacity', 'wheels', 'tool-storage'],
  'tool-sets': ['brand', 'pieces', 'tools-included', 'storage-included', 'material'],
  'tool-storage': ['brand', 'type', 'capacity', 'material', 'wheels', 'weather-resistant'],
  
  // Watering & Irrigation
  'watering-irrigation': ['brand', 'type', 'size', 'material', 'coverage'],
  'garden-hoses': ['brand', 'length', 'diameter', 'material', 'kink-resistant', 'expandable'],
  'hose-reels': ['brand', 'capacity', 'type', 'material', 'wall-cart-mounted'],
  'hose-nozzles': ['brand', 'material', 'spray-patterns', 'adjustable', 'shut-off'],
  'sprinklers': ['brand', 'type', 'coverage', 'adjustable', 'oscillating-rotary-impact'],
  'soaker-hoses': ['brand', 'length', 'diameter', 'material', 'water-saving'],
  'drip-irrigation': ['brand', 'length', 'emitters', 'flow-rate', 'kit-components'],
  'irrigation-timers': ['brand', 'zones', 'programs', 'battery-solar', 'wifi-enabled'],
  'watering-cans': ['brand', 'capacity', 'material', 'spout-type', 'handle-type'],
  'watering-wands': ['brand', 'length', 'spray-patterns', 'shut-off', 'adjustable'],
  'rain-barrels': ['brand', 'capacity', 'material', 'spigot', 'overflow', 'screen'],
  'water-pumps': ['brand', 'type', 'flow-rate', 'power-source', 'head-height'],
  'pressure-washers': ['brand', 'psi', 'gpm', 'power-source', 'hose-length', 'nozzles'],

  // Plants & Seeds
  'plants-seeds': ['brand', 'type', 'size', 'sun-requirements', 'hardiness-zone'],
  'vegetable-seeds': ['brand', 'variety', 'packet-size', 'organic', 'heirloom-hybrid', 'days-to-maturity'],
  'flower-seeds': ['brand', 'variety', 'packet-size', 'annual-perennial', 'sun-requirements', 'height'],
  'herb-seeds': ['brand', 'variety', 'packet-size', 'organic', 'culinary-medicinal'],
  'grass-seed': ['brand', 'weight', 'coverage', 'grass-type', 'sun-shade', 'climate'],
  'bulbs': ['brand', 'variety', 'quantity', 'size', 'bloom-time', 'hardiness-zone'],
  'live-plants': ['brand', 'variety', 'size', 'pot-size', 'sun-requirements', 'hardiness-zone'],
  'trees': ['brand', 'variety', 'height', 'pot-size', 'fruit-shade-ornamental', 'hardiness-zone'],
  'shrubs': ['brand', 'variety', 'height', 'pot-size', 'evergreen-deciduous', 'hardiness-zone'],
  'perennials': ['brand', 'variety', 'height', 'pot-size', 'bloom-time', 'sun-requirements'],
  'annuals': ['brand', 'variety', 'height', 'pot-size', 'bloom-time', 'sun-requirements'],
  'succulents': ['brand', 'variety', 'size', 'pot-size', 'indoor-outdoor', 'cold-hardy'],
  'cacti': ['brand', 'variety', 'size', 'pot-size', 'indoor-outdoor', 'cold-hardy'],
  'houseplants': ['brand', 'variety', 'size', 'pot-size', 'light-requirements', 'pet-safe'],
  'aquatic-plants': ['brand', 'variety', 'size', 'depth-range', 'sun-requirements', 'hardiness-zone'],
  
  // Planters & Containers
  'planters-containers': ['brand', 'size', 'material', 'color', 'drainage'],
  'flower-pots': ['brand', 'diameter', 'height', 'material', 'drainage-holes', 'saucer-included'],
  'hanging-baskets': ['brand', 'diameter', 'material', 'liner-included', 'chain-length'],
  'window-boxes': ['brand', 'length', 'width', 'material', 'drainage', 'mounting-brackets'],
  'raised-beds': ['brand', 'size', 'height', 'material', 'capacity', 'liner-included'],
  'planter-boxes': ['brand', 'size', 'material', 'drainage', 'legs-wheels', 'liner-included'],
  'self-watering-planters': ['brand', 'size', 'material', 'reservoir-capacity', 'indicator'],
  'vertical-planters': ['brand', 'pockets-tiers', 'size', 'material', 'wall-freestanding'],
  'grow-bags': ['brand', 'capacity', 'material', 'handles', 'drainage', 'quantity'],
  'seed-trays': ['brand', 'cells', 'size', 'material', 'dome-included', 'drainage'],
  'propagation-trays': ['brand', 'cells', 'size', 'humidity-dome', 'drainage', 'heat-mat-compatible'],

  // Garden Structures
  'garden-structures': ['brand', 'size', 'material', 'assembly-required', 'weather-resistant'],
  'greenhouses': ['brand', 'size', 'material', 'frame-material', 'vents', 'shelves'],
  'cold-frames': ['brand', 'size', 'material', 'lid-type', 'insulated'],
  'garden-sheds': ['brand', 'size', 'material', 'floor-included', 'windows', 'assembly'],
  'arbors': ['brand', 'height', 'width', 'material', 'arch-flat-top', 'gate'],
  'trellises': ['brand', 'height', 'width', 'material', 'freestanding-wall-mount', 'expandable'],
  'pergolas': ['brand', 'size', 'material', 'canopy-included', 'freestanding-attached'],
  'gazebos': ['brand', 'size', 'material', 'roof-type', 'mosquito-netting', 'sidewalls'],
  'garden-arches': ['brand', 'height', 'width', 'material', 'style'],
  'obelisks': ['brand', 'height', 'material', 'base-width', 'style'],
  'plant-cages': ['brand', 'height', 'diameter', 'material', 'rings', 'collapsible'],
  'tomato-cages': ['brand', 'height', 'diameter', 'material', 'legs', 'quantity'],
  'plant-supports': ['brand', 'height', 'type', 'material', 'adjustable', 'quantity'],
  'garden-netting': ['brand', 'size', 'mesh-size', 'material', 'bird-insect-deer'],
  'row-covers': ['brand', 'size', 'material', 'weight', 'frost-protection', 'uv-resistant'],
  'shade-cloth': ['brand', 'size', 'shade-percentage', 'material', 'grommets'],
  'fencing': ['brand', 'height', 'length', 'material', 'style', 'gate-included'],
  'garden-gates': ['brand', 'height', 'width', 'material', 'style', 'latch-type'],
  'privacy-screens': ['brand', 'height', 'length', 'material', 'expandable', 'freestanding-mounted'],
  
  // Outdoor Furniture
  'outdoor-furniture': ['brand', 'material', 'color', 'weather-resistant', 'assembly-required'],
  'patio-sets': ['brand', 'pieces', 'material', 'seating-capacity', 'cushions-included'],
  'outdoor-chairs': ['brand', 'material', 'style', 'stackable', 'cushion-included', 'weight-capacity'],
  'outdoor-tables': ['brand', 'size', 'material', 'shape', 'umbrella-hole', 'foldable'],
  'outdoor-benches': ['brand', 'length', 'material', 'seating-capacity', 'storage', 'cushion-included'],
  'outdoor-sofas': ['brand', 'seating-capacity', 'material', 'cushions-included', 'modular'],
  'outdoor-sectionals': ['brand', 'pieces', 'material', 'seating-capacity', 'cushions-included'],
  'adirondack-chairs': ['brand', 'material', 'color', 'foldable', 'cup-holder'],
  'rocking-chairs-outdoor': ['brand', 'material', 'weight-capacity', 'cushion-included'],
  'chaise-lounges': ['brand', 'material', 'adjustable', 'wheels', 'cushion-included'],
  'hammocks': ['brand', 'size', 'material', 'weight-capacity', 'stand-included', 'spreader-bar'],
  'hammock-stands': ['brand', 'length', 'material', 'weight-capacity', 'adjustable'],
  'porch-swings': ['brand', 'seating-capacity', 'material', 'chain-length', 'cushion-included'],
  'swing-chairs': ['brand', 'material', 'weight-capacity', 'stand-included', 'cushion-included'],
  'outdoor-ottomans': ['brand', 'size', 'material', 'storage', 'cushion-included'],
  'outdoor-side-tables': ['brand', 'size', 'material', 'shape', 'foldable'],
  'outdoor-coffee-tables': ['brand', 'size', 'material', 'shape', 'storage'],
  'outdoor-bar-sets': ['brand', 'pieces', 'material', 'seating-capacity', 'bar-height'],
  'outdoor-dining-sets': ['brand', 'pieces', 'material', 'seating-capacity', 'table-size'],
  'patio-umbrellas': ['brand', 'diameter', 'material', 'tilt', 'crank-push', 'base-included'],
  'umbrella-bases': ['brand', 'weight', 'material', 'pole-diameter', 'wheels'],
  'cantilever-umbrellas': ['brand', 'diameter', 'material', 'rotation', 'base-included'],
  'outdoor-cushions': ['brand', 'size', 'material', 'thickness', 'ties', 'weather-resistant'],
  'furniture-covers': ['brand', 'size', 'material', 'waterproof', 'uv-resistant', 'drawstring-zipper'],
  
  // Grills & Outdoor Cooking
  'grills-outdoor-cooking': ['brand', 'type', 'size', 'fuel-type', 'cooking-area'],
  'gas-grills': ['brand', 'burners', 'cooking-area', 'btu', 'side-burner', 'cart-built-in'],
  'charcoal-grills': ['brand', 'cooking-area', 'type', 'ash-catcher', 'wheels'],
  'pellet-grills': ['brand', 'cooking-area', 'hopper-capacity', 'temperature-range', 'wifi'],
  'electric-grills': ['brand', 'cooking-area', 'wattage', 'temperature-range', 'indoor-outdoor'],
  'smokers': ['brand', 'type', 'cooking-area', 'fuel-type', 'temperature-range', 'water-pan'],
  'portable-grills': ['brand', 'type', 'cooking-area', 'fuel-type', 'foldable', 'weight'],
  'grill-accessories': ['brand', 'type', 'material', 'compatibility'],
  'grill-covers': ['brand', 'size', 'material', 'waterproof', 'uv-resistant'],
  'grill-tools': ['brand', 'pieces', 'material', 'case-included', 'heat-resistant'],
  'grill-brushes': ['brand', 'bristle-type', 'handle-length', 'scraper'],
  'grill-grates': ['brand', 'size', 'material', 'compatibility', 'porcelain-cast-iron'],
  'pizza-ovens': ['brand', 'type', 'fuel-type', 'cooking-area', 'max-temperature', 'portable'],
  'outdoor-kitchens': ['brand', 'pieces', 'material', 'grill-included', 'storage'],
  'fire-pits': ['brand', 'size', 'material', 'fuel-type', 'screen-included', 'portable'],
  'fire-tables': ['brand', 'size', 'material', 'fuel-type', 'btu', 'cover-included'],
  'chimineas': ['brand', 'height', 'material', 'fuel-type', 'screen-included'],
  'outdoor-fireplaces': ['brand', 'height', 'material', 'fuel-type', 'chimney'],
  'patio-heaters': ['brand', 'type', 'fuel-type', 'btu', 'coverage-area', 'wheels'],
  
  // Outdoor Lighting
  'outdoor-lighting': ['brand', 'type', 'power-source', 'lumens', 'weather-resistant'],
  'string-lights': ['brand', 'length', 'bulbs', 'power-source', 'dimmable', 'connectable'],
  'solar-lights': ['brand', 'type', 'lumens', 'battery-capacity', 'auto-on-off'],
  'path-lights': ['brand', 'quantity', 'power-source', 'lumens', 'stake-height'],
  'spotlights': ['brand', 'lumens', 'power-source', 'adjustable', 'motion-sensor'],
  'flood-lights': ['brand', 'lumens', 'power-source', 'motion-sensor', 'coverage-angle'],
  'deck-lights': ['brand', 'quantity', 'power-source', 'lumens', 'mounting-type'],
  'post-cap-lights': ['brand', 'size', 'power-source', 'lumens', 'material'],
  'landscape-lighting': ['brand', 'type', 'power-source', 'lumens', 'adjustable'],
  'lanterns': ['brand', 'size', 'power-source', 'lumens', 'hanging-tabletop'],
  'tiki-torches': ['brand', 'height', 'material', 'fuel-type', 'quantity'],

  // Outdoor Decor
  'outdoor-decor': ['brand', 'size', 'material', 'color', 'weather-resistant'],
  'garden-statues': ['brand', 'height', 'material', 'subject', 'weight'],
  'garden-gnomes': ['brand', 'height', 'material', 'design', 'hand-painted'],
  'bird-baths': ['brand', 'height', 'diameter', 'material', 'pedestal-hanging'],
  'bird-feeders': ['brand', 'capacity', 'material', 'bird-type', 'squirrel-proof'],
  'bird-houses': ['brand', 'size', 'material', 'bird-type', 'mounting-type'],
  'wind-chimes': ['brand', 'length', 'material', 'tubes', 'sound-type'],
  'wind-spinners': ['brand', 'height', 'material', 'design', 'stake-hanging'],
  'garden-flags': ['brand', 'size', 'material', 'design', 'double-sided'],
  'flag-poles': ['brand', 'height', 'material', 'mounting-type', 'flag-size'],
  'garden-stakes-decor': ['brand', 'height', 'material', 'design', 'solar-powered'],
  'stepping-stones': ['brand', 'size', 'material', 'design', 'quantity'],
  'outdoor-rugs': ['brand', 'size', 'material', 'pattern', 'weather-resistant'],
  'door-mats': ['brand', 'size', 'material', 'design', 'scraper'],
  'planters-decorative': ['brand', 'size', 'material', 'design', 'drainage'],
  'fountains': ['brand', 'height', 'material', 'pump-included', 'solar-electric', 'capacity'],
  'water-features': ['brand', 'size', 'material', 'pump-included', 'lighting'],
  'pond-liners': ['brand', 'size', 'material', 'thickness', 'fish-safe'],
  'pond-pumps': ['brand', 'flow-rate', 'head-height', 'energy-efficient'],
  'pond-filters': ['brand', 'capacity', 'type', 'uv-clarifier', 'pump-included'],
  'mailboxes': ['brand', 'size', 'material', 'post-included', 'locking'],
  'address-plaques': ['brand', 'size', 'material', 'customizable', 'mounting-type'],
  'thermometers-outdoor': ['brand', 'type', 'temperature-range', 'humidity', 'wireless'],
  'weather-stations': ['brand', 'sensors', 'wireless-range', 'display-type', 'forecast'],
  'rain-gauges': ['brand', 'capacity', 'material', 'mounting-type', 'easy-read'],
  
  // Pest Control & Wildlife
  'pest-control-wildlife': ['brand', 'type', 'coverage', 'safe-for-pets'],
  'insect-traps': ['brand', 'insect-type', 'coverage', 'attractant-included', 'reusable'],
  'mosquito-traps': ['brand', 'coverage', 'power-source', 'attractant-type', 'refills'],
  'bug-zappers': ['brand', 'coverage', 'power-source', 'waterproof', 'cleaning-brush'],
  'citronella-candles': ['brand', 'size', 'burn-time', 'scent', 'container-type'],
  'mosquito-netting': ['brand', 'size', 'mesh-size', 'treatment', 'hanging-type'],
  'animal-repellents': ['brand', 'animal-type', 'coverage', 'organic', 'spray-granules'],
  'deer-repellent': ['brand', 'size', 'coverage', 'organic', 'spray-stakes'],
  'rodent-control': ['brand', 'type', 'quantity', 'humane', 'indoor-outdoor'],
  'live-traps': ['brand', 'size', 'animal-type', 'doors', 'rust-resistant'],
  'scarecrows': ['brand', 'height', 'material', 'motion-activated', 'solar-powered'],
  'bird-netting': ['brand', 'size', 'mesh-size', 'uv-resistant', 'reusable'],

  // Outdoor Recreation
  'outdoor-recreation': ['brand', 'size', 'material', 'age-group', 'weight-capacity'],
  'playsets': ['brand', 'size', 'material', 'features', 'age-group', 'assembly'],
  'swing-sets': ['brand', 'swings', 'weight-capacity', 'material', 'slide-included', 'age-group'],
  'slides': ['brand', 'height', 'material', 'age-group', 'weight-capacity', 'freestanding-attached'],
  'climbing-frames': ['brand', 'height', 'material', 'age-group', 'weight-capacity'],
  'sandboxes': ['brand', 'size', 'material', 'cover-included', 'seats', 'canopy'],
  'trampolines': ['brand', 'diameter', 'weight-capacity', 'safety-net', 'springs', 'ladder'],
  'basketball-hoops': ['brand', 'height-adjustable', 'backboard-size', 'portable-in-ground', 'weather-resistant'],
  'cornhole-sets': ['brand', 'board-size', 'material', 'bags-included', 'foldable'],
  'horseshoe-sets': ['brand', 'material', 'stakes-included', 'carrying-case'],
  'bocce-ball-sets': ['brand', 'balls-included', 'material', 'carrying-case'],
  'croquet-sets': ['brand', 'players', 'pieces', 'carrying-case'],
  'badminton-sets': ['brand', 'racquets', 'net-included', 'shuttlecocks', 'carrying-case'],
  'volleyball-sets': ['brand', 'net-height', 'poles-included', 'ball-included', 'portable'],
  'tetherball-sets': ['brand', 'pole-height', 'ball-included', 'in-ground-portable'],
  'outdoor-games': ['brand', 'type', 'players', 'age-group', 'portable'],
  
  // Pool & Spa
  'pool-spa': ['brand', 'size', 'type', 'capacity'],
  'above-ground-pools': ['brand', 'diameter', 'height', 'capacity', 'filter-included', 'ladder-included'],
  'inflatable-pools': ['brand', 'size', 'capacity', 'pump-included', 'age-group'],
  'pool-filters': ['brand', 'type', 'flow-rate', 'pool-size', 'cartridge-sand-de'],
  'pool-pumps': ['brand', 'horsepower', 'flow-rate', 'pool-size', 'energy-efficient'],
  'pool-cleaners': ['brand', 'type', 'power-source', 'pool-type', 'cord-length'],
  'pool-covers': ['brand', 'size', 'type', 'material', 'solar-winter-safety'],
  'pool-ladders': ['brand', 'steps', 'weight-capacity', 'material', 'above-in-ground'],
  'pool-chemicals': ['brand', 'type', 'size', 'purpose', 'chlorine-bromine'],
  'pool-test-kits': ['brand', 'parameters', 'tests-included', 'strips-liquid'],
  'pool-floats': ['brand', 'size', 'material', 'weight-capacity', 'cup-holders'],
  'pool-toys': ['brand', 'type', 'age-group', 'inflatable', 'diving-floating'],
  'hot-tubs': ['brand', 'capacity', 'jets', 'power-source', 'inflatable-hard-shell'],
  'spa-chemicals': ['brand', 'type', 'size', 'purpose', 'chlorine-bromine'],
  'spa-covers': ['brand', 'size', 'material', 'insulation', 'lifter-included'],
  
  // Snow Removal
  'snow-removal': ['brand', 'type', 'size', 'material', 'power-source'],
  'snow-shovels': ['brand', 'blade-width', 'handle-length', 'material', 'ergonomic'],
  'snow-pushers': ['brand', 'blade-width', 'handle-length', 'material', 'wheels'],
  'snow-blowers': ['brand', 'clearing-width', 'power-source', 'stages', 'throw-distance'],
  'ice-melt': ['brand', 'weight', 'type', 'coverage', 'pet-safe', 'temperature-rating'],
  'ice-scrapers': ['brand', 'length', 'material', 'brush-included', 'telescoping'],
  'roof-rakes': ['brand', 'reach', 'blade-width', 'material', 'wheels'],

  // Outdoor Storage
  'outdoor-storage': ['brand', 'size', 'material', 'capacity', 'weather-resistant'],
  'deck-boxes': ['brand', 'capacity', 'material', 'lockable', 'seat-top', 'waterproof'],
  'storage-sheds': ['brand', 'size', 'material', 'floor-included', 'windows', 'assembly'],
  'tool-sheds': ['brand', 'size', 'material', 'shelves', 'lockable', 'floor-included'],
  'bike-storage': ['brand', 'capacity', 'material', 'bikes', 'lockable', 'weather-resistant'],
  'garbage-can-storage': ['brand', 'capacity', 'material', 'cans', 'lockable', 'ventilation'],
  'firewood-racks': ['brand', 'capacity', 'material', 'cover-included', 'dimensions'],
  'hose-storage': ['brand', 'capacity', 'material', 'hose-length', 'wall-freestanding'],
  'cushion-storage': ['brand', 'capacity', 'material', 'waterproof', 'ventilation'],
  
  // Composting
  'composting': ['brand', 'capacity', 'material', 'type', 'assembly'],
  'compost-bins': ['brand', 'capacity', 'material', 'doors', 'ventilation', 'rodent-proof'],
  'compost-tumblers': ['brand', 'capacity', 'material', 'chambers', 'rotation', 'stand-included'],
  'compost-aerators': ['brand', 'length', 'material', 'type', 'handle'],
  'compost-thermometers': ['brand', 'length', 'temperature-range', 'dial-digital'],
  'kitchen-compost-bins': ['brand', 'capacity', 'material', 'filter-included', 'odor-control'],
  'worm-composters': ['brand', 'capacity', 'trays', 'material', 'worms-included'],
  
  // Greenhouses & Growing
  'greenhouses-growing': ['brand', 'size', 'material', 'type', 'assembly'],
  'mini-greenhouses': ['brand', 'size', 'shelves', 'material', 'cover-type', 'portable'],
  'grow-tents': ['brand', 'size', 'material', 'reflective', 'vents', 'observation-window'],
  'grow-lights': ['brand', 'wattage', 'spectrum', 'coverage', 'dimmable', 'timer'],
  'heat-mats': ['brand', 'size', 'wattage', 'temperature-range', 'waterproof'],
  'humidity-domes': ['brand', 'size', 'material', 'vents', 'tray-included'],
  'plant-stands': ['brand', 'tiers', 'size', 'material', 'weight-capacity', 'wheels'],
  'potting-benches': ['brand', 'size', 'material', 'storage', 'sink', 'work-surface'],
  
  // Outdoor Power Equipment
  'outdoor-power-equipment': ['brand', 'type', 'power-source', 'engine-size'],
  'generators': ['brand', 'wattage', 'fuel-type', 'runtime', 'outlets', 'electric-start'],
  'pressure-washers-power': ['brand', 'psi', 'gpm', 'power-source', 'hose-length', 'nozzles'],
  'log-splitters': ['brand', 'tonnage', 'power-source', 'log-length', 'cycle-time'],
  'wood-chippers': ['brand', 'capacity', 'power-source', 'reduction-ratio', 'bag-included'],
  'leaf-shredders': ['brand', 'capacity', 'power-source', 'reduction-ratio', 'bag-capacity'],
  'hedge-trimmers-power': ['brand', 'blade-length', 'power-source', 'tooth-spacing', 'rotating-head'],
  'pole-trimmers': ['brand', 'reach', 'power-source', 'blade-length', 'adjustable-head'],
  'cultivators-power': ['brand', 'tilling-width', 'power-source', 'tines', 'depth-adjustment'],
  
  // Safety & Maintenance
  'outdoor-safety': ['brand', 'type', 'size', 'certification'],
  'work-gloves': ['brand', 'size', 'material', 'grip', 'cut-resistant', 'waterproof'],
  'safety-glasses': ['brand', 'lens-type', 'uv-protection', 'anti-fog', 'adjustable'],
  'ear-protection': ['brand', 'type', 'nrr-rating', 'adjustable', 'foldable'],
  'knee-pads': ['brand', 'size', 'material', 'strap-type', 'gel-foam'],
  'tool-belts': ['brand', 'size', 'material', 'pockets', 'adjustable'],
  'first-aid-kits-outdoor': ['brand', 'pieces', 'case-type', 'waterproof'],
  'fire-extinguishers': ['brand', 'size', 'type', 'rating', 'rechargeable'],
};
