/**
 * Grocery & Food Category Attribute Mappings
 * 
 * Comprehensive mappings for food, beverages, and grocery items
 */

export const groceryFoodMappings = {
  // Main Grocery & Food
  'grocery-food': ['brand', 'size', 'weight', 'organic', 'dietary'],
  'food': ['brand', 'size', 'weight', 'organic', 'dietary', 'expiry-date'],
  'groceries': ['brand', 'size', 'weight', 'organic', 'pack-size'],
  
  // Fresh Produce
  'fresh-produce': ['organic', 'weight', 'origin', 'grade'],
  'fruits': ['type', 'organic', 'weight', 'origin', 'grade', 'ripe-level'],
  'vegetables': ['type', 'organic', 'weight', 'origin', 'grade', 'fresh-frozen'],
  'salad-greens': ['type', 'organic', 'weight', 'washed', 'pack-type'],
  'herbs': ['type', 'organic', 'weight', 'fresh-dried', 'origin'],
  'mushrooms': ['type', 'organic', 'weight', 'fresh-dried', 'sliced-whole'],
  
  // Meat & Seafood
  'meat-seafood': ['type', 'weight', 'cut', 'fresh-frozen', 'organic'],
  'beef': ['cut', 'weight', 'grade', 'grass-fed', 'organic', 'fresh-frozen'],
  'pork': ['cut', 'weight', 'organic', 'fresh-frozen', 'bone-in-boneless'],
  'chicken': ['cut', 'weight', 'organic', 'free-range', 'fresh-frozen', 'bone-in-boneless'],
  'turkey': ['cut', 'weight', 'organic', 'free-range', 'fresh-frozen', 'whole-parts'],
  'lamb': ['cut', 'weight', 'organic', 'grass-fed', 'fresh-frozen'],
  'seafood': ['type', 'weight', 'fresh-frozen', 'wild-farmed', 'cleaned'],
  'fish': ['type', 'weight', 'fresh-frozen', 'wild-farmed', 'fillet-whole', 'boneless'],
  'shellfish': ['type', 'weight', 'fresh-frozen', 'wild-farmed', 'cleaned', 'cooked-raw'],
  'deli-meat': ['type', 'weight', 'sliced-whole', 'organic', 'nitrate-free'],
  'bacon': ['type', 'weight', 'cut', 'smoked', 'nitrate-free', 'organic'],
  'sausages': ['type', 'weight', 'casing', 'cooked-raw', 'links-bulk'],
  'hot-dogs': ['type', 'weight', 'count', 'casing', 'nitrate-free'],
  
  // Dairy & Eggs
  'dairy-eggs': ['brand', 'size', 'organic', 'fat-content'],
  'milk': ['brand', 'size', 'fat-content', 'organic', 'lactose-free', 'type'],
  'cheese': ['type', 'weight', 'organic', 'aged', 'sliced-block-shredded'],
  'yogurt': ['brand', 'size', 'flavor', 'fat-content', 'organic', 'greek-regular', 'probiotic'],
  'butter': ['brand', 'weight', 'salted-unsalted', 'organic', 'grass-fed'],
  'cream': ['brand', 'size', 'fat-content', 'organic', 'whipping-heavy'],
  'sour-cream': ['brand', 'size', 'fat-content', 'organic'],
  'cottage-cheese': ['brand', 'size', 'fat-content', 'organic', 'curd-size'],
  'cream-cheese': ['brand', 'size', 'flavor', 'fat-content', 'organic'],
  'eggs': ['size', 'quantity', 'organic', 'free-range', 'cage-free', 'omega-3'],
  'ice-cream': ['brand', 'flavor', 'size', 'fat-content', 'dairy-free'],
  'frozen-yogurt': ['brand', 'flavor', 'size', 'fat-content', 'probiotic'],
  
  // Bakery
  'bakery': ['brand', 'size', 'weight', 'whole-grain', 'organic'],
  'bread': ['brand', 'type', 'size', 'whole-grain', 'organic', 'sliced-unsliced'],
  'bagels': ['brand', 'flavor', 'count', 'whole-grain', 'organic'],
  'rolls': ['brand', 'type', 'count', 'whole-grain', 'organic'],
  'buns': ['brand', 'type', 'count', 'whole-grain', 'sesame'],
  'tortillas': ['brand', 'type', 'count', 'size', 'whole-grain', 'flour-corn'],
  'pita-bread': ['brand', 'count', 'size', 'whole-grain', 'pocket'],
  'naan': ['brand', 'count', 'flavor', 'whole-grain'],
  'croissants': ['brand', 'count', 'butter-margarine', 'filled'],
  'muffins': ['brand', 'flavor', 'count', 'size', 'whole-grain'],
  'donuts': ['brand', 'flavor', 'count', 'filled-glazed'],
  'cakes': ['brand', 'flavor', 'size', 'layers', 'frosted', 'occasion'],
  'cookies': ['brand', 'flavor', 'weight', 'count', 'soft-crispy'],
  'pastries': ['brand', 'type', 'count', 'filled', 'frozen-fresh'],
  'pies': ['brand', 'flavor', 'size', 'frozen-fresh', 'baked-unbaked'],
  
  // Pantry Staples
  'pantry-staples': ['brand', 'size', 'weight', 'organic'],
  'rice': ['brand', 'type', 'weight', 'organic', 'white-brown', 'grain-length'],
  'pasta': ['brand', 'type', 'weight', 'whole-grain', 'organic', 'shape'],
  'noodles': ['brand', 'type', 'weight', 'instant-regular', 'wheat-rice'],
  'flour': ['brand', 'type', 'weight', 'organic', 'bleached-unbleached', 'all-purpose-bread'],
  'sugar': ['brand', 'type', 'weight', 'organic', 'white-brown', 'granulated-powdered'],
  'salt': ['brand', 'type', 'weight', 'iodized', 'sea-table', 'fine-coarse'],
  'cooking-oil': ['brand', 'type', 'size', 'organic', 'refined-unrefined'],
  'olive-oil': ['brand', 'size', 'organic', 'extra-virgin', 'origin'],
  'vegetable-oil': ['brand', 'type', 'size', 'organic'],
  'coconut-oil': ['brand', 'size', 'organic', 'refined-unrefined', 'virgin'],
  'vinegar': ['brand', 'type', 'size', 'organic', 'filtered-unfiltered'],
  'soy-sauce': ['brand', 'size', 'organic', 'low-sodium', 'gluten-free'],
  'hot-sauce': ['brand', 'size', 'heat-level', 'flavor', 'organic'],
  'ketchup': ['brand', 'size', 'organic', 'sugar-free', 'squeeze-bottle'],
  'mustard': ['brand', 'type', 'size', 'organic', 'spicy-mild'],
  'mayonnaise': ['brand', 'size', 'organic', 'fat-content', 'flavor'],
  'salad-dressing': ['brand', 'flavor', 'size', 'organic', 'fat-content'],
  'bbq-sauce': ['brand', 'flavor', 'size', 'organic', 'spicy-sweet'],
  'pasta-sauce': ['brand', 'flavor', 'size', 'organic', 'chunky-smooth'],
  'salsa': ['brand', 'heat-level', 'size', 'organic', 'chunky-smooth'],
  'peanut-butter': ['brand', 'size', 'organic', 'crunchy-smooth', 'natural', 'sugar-free'],
  'jelly-jam': ['brand', 'flavor', 'size', 'organic', 'sugar-content', 'seedless'],
  'honey': ['brand', 'size', 'organic', 'raw-processed', 'origin', 'flavor'],
  'maple-syrup': ['brand', 'size', 'organic', 'grade', 'pure'],
  
  // Canned & Jarred
  'canned-jarred': ['brand', 'size', 'weight', 'organic', 'low-sodium'],
  'canned-vegetables': ['brand', 'type', 'size', 'organic', 'low-sodium', 'whole-cut-diced'],
  'canned-fruits': ['brand', 'type', 'size', 'organic', 'syrup-juice-water'],
  'canned-beans': ['brand', 'type', 'size', 'organic', 'low-sodium', 'cooked-dried'],
  'canned-soup': ['brand', 'flavor', 'size', 'organic', 'low-sodium', 'condensed-ready'],
  'canned-tomatoes': ['brand', 'type', 'size', 'organic', 'whole-diced-crushed'],
  'tomato-paste': ['brand', 'size', 'organic', 'tube-can'],
  'canned-fish': ['brand', 'type', 'size', 'oil-water', 'wild-farmed'],
  'pickles': ['brand', 'type', 'size', 'organic', 'whole-sliced-spears', 'dill-sweet'],
  'olives': ['brand', 'type', 'size', 'organic', 'pitted', 'stuffed'],
  'capers': ['brand', 'size', 'organic', 'size-grade'],
  
  // Frozen Foods
  'frozen-foods': ['brand', 'weight', 'size', 'organic', 'servings'],
  'frozen-vegetables': ['brand', 'type', 'weight', 'organic', 'cut-style', 'steamer-bag'],
  'frozen-fruits': ['brand', 'type', 'weight', 'organic', 'whole-sliced'],
  'frozen-meals': ['brand', 'type', 'weight', 'servings', 'calories', 'dietary'],
  'frozen-pizza': ['brand', 'size', 'toppings', 'crust-type', 'servings'],
  'frozen-appetizers': ['brand', 'type', 'count', 'weight', 'oven-microwave'],
  'frozen-desserts': ['brand', 'type', 'size', 'servings', 'flavor'],
  'frozen-breakfast': ['brand', 'type', 'count', 'weight', 'oven-microwave'],
  'frozen-potatoes': ['brand', 'type', 'weight', 'cut-style', 'seasoned'],
  'frozen-seafood': ['brand', 'type', 'weight', 'wild-farmed', 'breaded-plain'],
  'frozen-meat': ['brand', 'type', 'weight', 'cut', 'marinated'],
  'ice-pops': ['brand', 'flavor', 'count', 'sugar-free', 'fruit-based'],
  
  // Snacks
  'snacks': ['brand', 'flavor', 'size', 'weight', 'organic'],
  'chips': ['brand', 'flavor', 'size', 'organic', 'baked-fried', 'potato-corn'],
  'pretzels': ['brand', 'flavor', 'size', 'organic', 'hard-soft', 'salted'],
  'popcorn': ['brand', 'flavor', 'size', 'organic', 'microwave-ready', 'butter'],
  'crackers': ['brand', 'flavor', 'size', 'whole-grain', 'organic', 'salted'],
  'nuts': ['brand', 'type', 'size', 'organic', 'roasted-raw', 'salted-unsalted'],
  'trail-mix': ['brand', 'size', 'organic', 'ingredients', 'chocolate'],
  'dried-fruit': ['brand', 'type', 'size', 'organic', 'sweetened-unsweetened', 'sulfur-free'],
  'granola-bars': ['brand', 'flavor', 'count', 'organic', 'protein', 'chewy-crunchy'],
  'protein-bars': ['brand', 'flavor', 'count', 'protein-content', 'calories', 'dietary'],
  'energy-bars': ['brand', 'flavor', 'count', 'calories', 'organic', 'dietary'],
  'fruit-snacks': ['brand', 'flavor', 'count', 'organic', 'real-fruit', 'gummy'],
  'jerky': ['brand', 'type', 'size', 'flavor', 'organic', 'grass-fed'],
  'rice-cakes': ['brand', 'flavor', 'count', 'organic', 'whole-grain'],
  'veggie-chips': ['brand', 'type', 'size', 'organic', 'baked-fried'],
  
  // Candy & Chocolate
  'candy-chocolate': ['brand', 'type', 'size', 'weight', 'flavor'],
  'chocolate': ['brand', 'type', 'size', 'cocoa-percentage', 'dark-milk-white'],
  'chocolate-bars': ['brand', 'flavor', 'size', 'dark-milk-white', 'filled'],
  'candy-bars': ['brand', 'flavor', 'size', 'chocolate-coated'],
  'gummy-candy': ['brand', 'flavor', 'size', 'shape', 'sour-sweet'],
  'hard-candy': ['brand', 'flavor', 'size', 'sugar-free', 'filled'],
  'lollipops': ['brand', 'flavor', 'count', 'size', 'filled'],
  'mints': ['brand', 'flavor', 'count', 'sugar-free', 'breath-freshening'],
  'gum': ['brand', 'flavor', 'count', 'sugar-free', 'bubble-chewing'],
  'licorice': ['brand', 'flavor', 'size', 'red-black', 'twists-bites'],
  
  // Beverages
  'beverages': ['brand', 'flavor', 'size', 'pack-size', 'sugar-content'],
  'water': ['brand', 'size', 'pack-size', 'sparkling-still', 'flavored', 'mineral-spring'],
  'soda': ['brand', 'flavor', 'size', 'pack-size', 'sugar-free', 'caffeine'],
  'juice': ['brand', 'flavor', 'size', 'organic', 'pulp', 'from-concentrate'],
  'sports-drinks': ['brand', 'flavor', 'size', 'electrolytes', 'sugar-content', 'pack-size'],
  'energy-drinks': ['brand', 'flavor', 'size', 'caffeine-content', 'sugar-free', 'pack-size'],
  'iced-tea': ['brand', 'flavor', 'size', 'sweetened-unsweetened', 'pack-size'],
  'lemonade': ['brand', 'flavor', 'size', 'organic', 'sugar-content'],
  'coffee-drinks': ['brand', 'flavor', 'size', 'hot-cold', 'sweetened', 'dairy-free'],
  'milk-alternatives': ['brand', 'type', 'size', 'organic', 'sweetened-unsweetened', 'fortified'],
  'almond-milk': ['brand', 'size', 'organic', 'sweetened-unsweetened', 'vanilla-original'],
  'soy-milk': ['brand', 'size', 'organic', 'sweetened-unsweetened', 'fortified'],
  'oat-milk': ['brand', 'size', 'organic', 'sweetened-unsweetened', 'barista-blend'],
  'coconut-milk': ['brand', 'size', 'organic', 'full-fat-light', 'canned-carton'],
  'protein-shakes': ['brand', 'flavor', 'size', 'protein-content', 'ready-to-drink-powder'],
  'smoothies': ['brand', 'flavor', 'size', 'organic', 'protein', 'frozen-refrigerated'],
  
  // Coffee & Tea
  'coffee-tea': ['brand', 'type', 'size', 'organic', 'caffeine'],
  'coffee-beans': ['brand', 'roast', 'weight', 'organic', 'origin', 'whole-ground'],
  'ground-coffee': ['brand', 'roast', 'weight', 'organic', 'origin', 'grind-size'],
  'instant-coffee': ['brand', 'size', 'organic', 'freeze-dried', 'decaf'],
  'coffee-pods': ['brand', 'roast', 'count', 'organic', 'compatibility', 'flavor'],
  'espresso': ['brand', 'roast', 'weight', 'organic', 'origin', 'whole-ground'],
  'decaf-coffee': ['brand', 'roast', 'weight', 'organic', 'method', 'whole-ground'],
  'tea-bags': ['brand', 'type', 'count', 'organic', 'caffeine', 'flavor'],
  'loose-tea': ['brand', 'type', 'weight', 'organic', 'caffeine', 'origin'],
  'green-tea': ['brand', 'count', 'organic', 'flavor', 'bags-loose'],
  'black-tea': ['brand', 'count', 'organic', 'flavor', 'bags-loose'],
  'herbal-tea': ['brand', 'flavor', 'count', 'organic', 'caffeine-free'],
  'chai-tea': ['brand', 'count', 'organic', 'spiced', 'bags-loose'],
  'matcha': ['brand', 'weight', 'organic', 'grade', 'ceremonial-culinary'],
  
  // Breakfast Foods
  'breakfast-foods': ['brand', 'size', 'weight', 'whole-grain', 'organic'],
  'cereal': ['brand', 'flavor', 'size', 'whole-grain', 'organic', 'sugar-content', 'hot-cold'],
  'oatmeal': ['brand', 'type', 'size', 'organic', 'instant-rolled-steel-cut', 'flavored'],
  'granola': ['brand', 'flavor', 'size', 'organic', 'clusters', 'sugar-content'],
  'pancake-mix': ['brand', 'size', 'whole-grain', 'organic', 'buttermilk', 'just-add-water'],
  'waffle-mix': ['brand', 'size', 'whole-grain', 'organic', 'belgian'],
  'syrup': ['brand', 'flavor', 'size', 'organic', 'pure-maple', 'sugar-free'],
  'breakfast-bars': ['brand', 'flavor', 'count', 'whole-grain', 'organic', 'protein'],
  'toaster-pastries': ['brand', 'flavor', 'count', 'frosted', 'whole-grain'],
  'frozen-waffles': ['brand', 'flavor', 'count', 'whole-grain', 'organic'],
  'frozen-pancakes': ['brand', 'flavor', 'count', 'whole-grain', 'organic'],
  
  // Baking Supplies
  'baking-supplies': ['brand', 'size', 'weight', 'organic'],
  'baking-powder': ['brand', 'size', 'organic', 'aluminum-free'],
  'baking-soda': ['brand', 'size', 'food-grade'],
  'yeast': ['brand', 'size', 'type', 'organic', 'active-instant'],
  'vanilla-extract': ['brand', 'size', 'organic', 'pure-imitation'],
  'chocolate-chips': ['brand', 'size', 'type', 'organic', 'dark-milk-white'],
  'cocoa-powder': ['brand', 'size', 'organic', 'dutch-natural', 'unsweetened'],
  'baking-chocolate': ['brand', 'size', 'type', 'unsweetened-semisweet'],
  'sprinkles': ['brand', 'size', 'color', 'shape', 'sugar-nonpareils'],
  'food-coloring': ['brand', 'colors', 'type', 'gel-liquid', 'natural'],
  'cake-mix': ['brand', 'flavor', 'size', 'servings', 'frosting-included'],
  'brownie-mix': ['brand', 'flavor', 'size', 'servings', 'fudgy-cakey'],
  'cookie-mix': ['brand', 'flavor', 'size', 'servings', 'type'],
  'frosting': ['brand', 'flavor', 'size', 'ready-to-use', 'color'],
  'pie-crust': ['brand', 'count', 'size', 'refrigerated-frozen', 'deep-dish'],
  'puff-pastry': ['brand', 'count', 'size', 'sheets', 'butter'],
  
  // Condiments & Sauces
  'condiments-sauces': ['brand', 'size', 'organic', 'flavor'],
  'steak-sauce': ['brand', 'size', 'flavor', 'organic'],
  'worcestershire-sauce': ['brand', 'size', 'organic', 'gluten-free'],
  'fish-sauce': ['brand', 'size', 'origin', 'sodium-content'],
  'teriyaki-sauce': ['brand', 'size', 'organic', 'low-sodium', 'gluten-free'],
  'hoisin-sauce': ['brand', 'size', 'organic', 'gluten-free'],
  'sriracha': ['brand', 'size', 'heat-level', 'organic'],
  'chili-sauce': ['brand', 'size', 'heat-level', 'organic', 'sweet-spicy'],
  'cocktail-sauce': ['brand', 'size', 'horseradish-content'],
  'tartar-sauce': ['brand', 'size', 'organic', 'pickle-relish'],
  'gravy': ['brand', 'type', 'size', 'organic', 'jar-packet'],
  'enchilada-sauce': ['brand', 'size', 'heat-level', 'organic', 'red-green'],
  'taco-sauce': ['brand', 'size', 'heat-level', 'organic'],
  'buffalo-sauce': ['brand', 'size', 'heat-level', 'butter-content'],
  'wing-sauce': ['brand', 'flavor', 'size', 'heat-level'],
  
  // Spices & Seasonings
  'spices-seasonings': ['brand', 'size', 'weight', 'organic', 'ground-whole'],
  'salt-pepper': ['brand', 'type', 'size', 'organic', 'grinder-shaker'],
  'garlic-powder': ['brand', 'size', 'organic', 'granulated'],
  'onion-powder': ['brand', 'size', 'organic', 'granulated'],
  'paprika': ['brand', 'size', 'organic', 'smoked-sweet', 'ground'],
  'chili-powder': ['brand', 'size', 'organic', 'heat-level'],
  'cumin': ['brand', 'size', 'organic', 'ground-whole'],
  'cinnamon': ['brand', 'size', 'organic', 'ground-sticks'],
  'oregano': ['brand', 'size', 'organic', 'ground-leaves'],
  'basil': ['brand', 'size', 'organic', 'ground-leaves'],
  'thyme': ['brand', 'size', 'organic', 'ground-leaves'],
  'rosemary': ['brand', 'size', 'organic', 'ground-leaves'],
  'bay-leaves': ['brand', 'size', 'organic', 'whole'],
  'curry-powder': ['brand', 'size', 'organic', 'heat-level', 'blend-type'],
  'italian-seasoning': ['brand', 'size', 'organic', 'salt-free'],
  'taco-seasoning': ['brand', 'size', 'organic', 'heat-level', 'packet-jar'],
  'cajun-seasoning': ['brand', 'size', 'organic', 'heat-level', 'salt-content'],
  'everything-bagel-seasoning': ['brand', 'size', 'organic', 'ingredients'],
  'seasoning-blends': ['brand', 'type', 'size', 'organic', 'salt-free'],
  
  // International Foods
  'international-foods': ['brand', 'cuisine', 'size', 'weight', 'organic'],
  'asian-foods': ['brand', 'type', 'size', 'origin', 'organic'],
  'mexican-foods': ['brand', 'type', 'size', 'organic', 'heat-level'],
  'italian-foods': ['brand', 'type', 'size', 'organic', 'imported'],
  'indian-foods': ['brand', 'type', 'size', 'organic', 'heat-level'],
  'middle-eastern-foods': ['brand', 'type', 'size', 'organic', 'origin'],
  
  // Health & Specialty Foods
  'health-specialty': ['brand', 'size', 'dietary', 'organic', 'certification'],
  'gluten-free': ['brand', 'type', 'size', 'certified', 'organic'],
  'vegan': ['brand', 'type', 'size', 'certified', 'organic'],
  'keto': ['brand', 'type', 'size', 'net-carbs', 'organic'],
  'paleo': ['brand', 'type', 'size', 'certified', 'organic'],
  'low-carb': ['brand', 'type', 'size', 'net-carbs', 'sugar-content'],
  'sugar-free': ['brand', 'type', 'size', 'sweetener-type', 'calories'],
  'low-sodium': ['brand', 'type', 'size', 'sodium-content'],
  'high-protein': ['brand', 'type', 'size', 'protein-content', 'source'],
  'organic-foods': ['brand', 'type', 'size', 'certification', 'origin'],
  'non-gmo': ['brand', 'type', 'size', 'verified', 'organic'],
  
  // Baby Food
  'baby-food': ['brand', 'stage', 'flavor', 'size', 'organic'],
  'baby-formula': ['brand', 'stage', 'size', 'type', 'organic', 'iron-fortified'],
  'baby-cereal': ['brand', 'type', 'size', 'organic', 'iron-fortified', 'stage'],
  'baby-purees': ['brand', 'flavor', 'size', 'stage', 'organic', 'pouch-jar'],
  'toddler-snacks': ['brand', 'flavor', 'size', 'organic', 'age-group', 'allergen-free'],
  
  // Pet Food
  'pet-food': ['brand', 'pet-type', 'size', 'weight', 'age-group'],
  'dog-food': ['brand', 'size', 'age-group', 'breed-size', 'dry-wet', 'grain-free'],
  'cat-food': ['brand', 'size', 'age-group', 'dry-wet', 'grain-free', 'indoor-outdoor'],
  'pet-treats': ['brand', 'pet-type', 'size', 'flavor', 'training-dental'],
};
