export const healthBeautyMappings = {
  // ==========================================
  // HEALTH & BEAUTY
  // ==========================================
  
  // Main Health & Beauty Category
  'health-beauty': ['brand', 'size', 'scent', 'skin-type', 'gender'],
  'beauty': ['brand', 'size', 'color', 'scent', 'skin-type'],
  
  // Skincare
  'skincare': ['brand', 'size', 'skin-type', 'spf', 'ingredients', 'age-group'],
  'face-wash': ['brand', 'size', 'skin-type', 'ingredients', 'scent'],
  'facial-cleansers': ['brand', 'size', 'skin-type', 'form', 'ingredients'],
  'moisturizers': ['brand', 'size', 'skin-type', 'spf', 'day-night'],
  'face-creams': ['brand', 'size', 'skin-type', 'spf', 'anti-aging'],
  'serums': ['brand', 'size', 'skin-type', 'ingredients', 'concern'],
  'face-oils': ['brand', 'size', 'skin-type', 'ingredients'],
  'toners': ['brand', 'size', 'skin-type', 'alcohol-free'],
  'exfoliators': ['brand', 'size', 'skin-type', 'type', 'frequency'],
  'face-masks': ['brand', 'size', 'skin-type', 'type', 'concern'],
  'sheet-masks': ['brand', 'skin-type', 'ingredients', 'pack-size'],
  'eye-cream': ['brand', 'size', 'concern', 'age-group'],
  'sunscreen': ['brand', 'size', 'spf', 'water-resistant', 'skin-type'],
  'acne-treatment': ['brand', 'size', 'active-ingredient', 'skin-type'],
  'anti-aging': ['brand', 'size', 'type', 'ingredients', 'age-group'],
  'body-lotion': ['brand', 'size', 'skin-type', 'scent', 'spf'],
  'body-butter': ['brand', 'size', 'scent', 'ingredients'],
  'hand-cream': ['brand', 'size', 'scent', 'fast-absorbing'],
  'foot-cream': ['brand', 'size', 'concern', 'ingredients'],
  
  // Makeup
  'makeup': ['brand', 'color', 'shade', 'finish', 'skin-type'],
  'foundation': ['brand', 'shade', 'finish', 'skin-type', 'coverage', 'spf'],
  'concealer': ['brand', 'shade', 'coverage', 'skin-type', 'concern'],
  'powder': ['brand', 'shade', 'finish', 'skin-type', 'pressed-loose'],
  'blush': ['brand', 'color', 'finish', 'skin-type', 'form'],
  'bronzer': ['brand', 'shade', 'finish', 'skin-type'],
  'highlighter': ['brand', 'shade', 'finish', 'form'],
  'contour': ['brand', 'shade', 'form', 'skin-type'],
  'primer': ['brand', 'type', 'skin-type', 'finish'],
  'setting-spray': ['brand', 'size', 'finish', 'skin-type'],
  'lipstick': ['brand', 'color', 'finish', 'long-lasting', 'moisturizing'],
  'lip-gloss': ['brand', 'color', 'finish', 'plumping'],
  'lip-liner': ['brand', 'color', 'long-lasting', 'waterproof'],
  'lip-balm': ['brand', 'flavor', 'spf', 'tinted'],
  'eyeshadow': ['brand', 'color', 'finish', 'palette-size', 'pigmentation'],
  'eyeshadow-palette': ['brand', 'colors', 'finish', 'theme'],
  'eyeliner': ['brand', 'color', 'type', 'waterproof', 'long-lasting'],
  'mascara': ['brand', 'color', 'waterproof', 'volume', 'lengthening'],
  'eyebrow-pencil': ['brand', 'color', 'type', 'waterproof'],
  'eyebrow-gel': ['brand', 'color', 'hold', 'tinted'],
  'false-lashes': ['brand', 'style', 'length', 'reusable'],
  'makeup-remover': ['brand', 'size', 'type', 'skin-type', 'waterproof'],
  'makeup-brushes': ['brand', 'type', 'material', 'set-size'],
  'makeup-sponges': ['brand', 'type', 'material', 'pack-size'],
  
  // Haircare
  'haircare': ['brand', 'size', 'hair-type', 'scent', 'concern'],
  'shampoo': ['brand', 'size', 'hair-type', 'scent', 'sulfate-free'],
  'conditioner': ['brand', 'size', 'hair-type', 'scent', 'leave-in'],
  'hair-masks': ['brand', 'size', 'hair-type', 'concern'],
  'hair-oil': ['brand', 'size', 'hair-type', 'ingredients'],
  'hair-serum': ['brand', 'size', 'hair-type', 'concern'],
  'hair-styling': ['brand', 'size', 'hair-type', 'hold', 'finish'],
  'hair-gel': ['brand', 'size', 'hold', 'shine'],
  'hair-mousse': ['brand', 'size', 'hold', 'volume'],
  'hair-spray': ['brand', 'size', 'hold', 'finish'],
  'hair-wax': ['brand', 'size', 'hold', 'shine'],
  'hair-pomade': ['brand', 'size', 'hold', 'shine'],
  'dry-shampoo': ['brand', 'size', 'scent', 'hair-color'],
  'hair-color': ['brand', 'color', 'type', 'permanent', 'ammonia-free'],
  'hair-dye': ['brand', 'color', 'type', 'duration'],
  'hair-bleach': ['brand', 'volume', 'type'],
  'hair-treatment': ['brand', 'size', 'concern', 'type'],
  'anti-dandruff': ['brand', 'size', 'active-ingredient'],
  'hair-growth': ['brand', 'size', 'type', 'ingredients'],
  'hair-tools': ['brand', 'type', 'heat-settings', 'material'],
  'hair-dryers': ['brand', 'wattage', 'heat-settings', 'attachments'],
  'hair-straighteners': ['brand', 'plate-material', 'heat-settings', 'plate-width'],
  'curling-irons': ['brand', 'barrel-size', 'heat-settings', 'material'],
  'hair-brushes': ['brand', 'type', 'bristle-type', 'size'],
  'hair-combs': ['brand', 'type', 'material', 'teeth-spacing'],
  
  // Fragrance
  'fragrance': ['brand', 'size', 'scent', 'gender', 'concentration'],
  'perfume': ['brand', 'size', 'scent', 'gender', 'concentration', 'notes'],
  'eau-de-parfum': ['brand', 'size', 'scent', 'gender', 'notes'],
  'eau-de-toilette': ['brand', 'size', 'scent', 'gender', 'notes'],
  'cologne': ['brand', 'size', 'scent', 'concentration'],
  'body-spray': ['brand', 'size', 'scent', 'gender'],
  'body-mist': ['brand', 'size', 'scent', 'gender'],
  'fragrance-sets': ['brand', 'pieces', 'scent', 'gender'],
  
  // Personal Care
  'personal-care': ['brand', 'size', 'scent', 'type'],
  'deodorant': ['brand', 'size', 'scent', 'type', 'gender', 'aluminum-free'],
  'antiperspirant': ['brand', 'size', 'scent', 'gender', 'protection-hours'],
  'body-wash': ['brand', 'size', 'scent', 'skin-type', 'moisturizing'],
  'shower-gel': ['brand', 'size', 'scent', 'skin-type'],
  'bar-soap': ['brand', 'scent', 'skin-type', 'pack-size'],
  'hand-soap': ['brand', 'size', 'scent', 'antibacterial', 'moisturizing'],
  'hand-sanitizer': ['brand', 'size', 'scent', 'alcohol-percentage'],
  'bath-salts': ['brand', 'size', 'scent', 'benefits'],
  'bath-bombs': ['brand', 'scent', 'ingredients', 'pack-size'],
  'bubble-bath': ['brand', 'size', 'scent', 'moisturizing'],
  
  // Oral Care
  'oral-care': ['brand', 'size', 'flavor', 'type'],
  'toothpaste': ['brand', 'size', 'flavor', 'whitening', 'fluoride'],
  'toothbrush': ['brand', 'type', 'bristle-softness', 'head-size'],
  'electric-toothbrush': ['brand', 'type', 'modes', 'battery-life'],
  'mouthwash': ['brand', 'size', 'flavor', 'alcohol-free', 'whitening'],
  'dental-floss': ['brand', 'length', 'flavor', 'waxed'],
  'teeth-whitening': ['brand', 'type', 'treatment-duration'],
  'denture-care': ['brand', 'size', 'type'],
  
  // Shaving & Hair Removal
  'shaving': ['brand', 'type', 'gender', 'size'],
  'razors': ['brand', 'type', 'gender', 'blade-count'],
  'electric-shavers': ['brand', 'type', 'gender', 'wet-dry', 'battery-life'],
  'shaving-cream': ['brand', 'size', 'scent', 'gender', 'skin-type'],
  'shaving-gel': ['brand', 'size', 'scent', 'gender'],
  'aftershave': ['brand', 'size', 'scent', 'alcohol-free'],
  'hair-removal-cream': ['brand', 'size', 'body-part', 'skin-type'],
  'wax-strips': ['brand', 'body-part', 'skin-type', 'count'],
  'epilators': ['brand', 'type', 'wet-dry', 'speed-settings'],
  
  // Nail Care
  'nail-care': ['brand', 'color', 'type', 'finish'],
  'nail-polish': ['brand', 'color', 'finish', 'quick-dry'],
  'gel-polish': ['brand', 'color', 'finish', 'led-uv'],
  'nail-polish-remover': ['brand', 'size', 'acetone-free', 'scent'],
  'nail-treatment': ['brand', 'size', 'type', 'concern'],
  'nail-tools': ['brand', 'type', 'material'],
  'nail-clippers': ['brand', 'type', 'size'],
  'nail-files': ['brand', 'grit', 'type', 'pack-size'],
  'cuticle-care': ['brand', 'type', 'size'],
  'artificial-nails': ['brand', 'type', 'length', 'count'],
  
  // Men's Grooming
  'mens-grooming': ['brand', 'type', 'scent', 'size'],
  'beard-oil': ['brand', 'size', 'scent', 'ingredients'],
  'beard-balm': ['brand', 'size', 'scent', 'hold'],
  'beard-wash': ['brand', 'size', 'scent'],
  'beard-trimmer': ['brand', 'length-settings', 'battery-life', 'wet-dry'],
  'hair-clippers': ['brand', 'length-settings', 'attachments', 'battery-life'],
  
  // Beauty Tools & Accessories
  'beauty-tools': ['brand', 'type', 'material', 'use'],
  'makeup-mirrors': ['brand', 'size', 'magnification', 'lighting'],
  'facial-cleansing-brush': ['brand', 'type', 'speed-settings', 'waterproof'],
  'jade-roller': ['brand', 'material', 'type'],
  'gua-sha': ['brand', 'material', 'shape'],
  'eyelash-curler': ['brand', 'type', 'material'],
  'tweezers': ['brand', 'type', 'tip-shape'],
  'cosmetic-bags': ['brand', 'size', 'material', 'compartments'],
  
  // Add more categories as needed...
};