/**
 * Health & Wellness Category Attribute Mappings
 * 
 * Comprehensive mappings for health, wellness, and medical products
 */

export const healthWellnessMappings = {
  // Main Health & Wellness
  'health-wellness': ['brand', 'type', 'size', 'purpose', 'age-group'],
  'health': ['brand', 'type', 'size', 'purpose', 'prescription-otc'],
  'wellness': ['brand', 'type', 'size', 'natural', 'organic'],
  
  // Vitamins & Supplements
  'vitamins-supplements': ['brand', 'type', 'size', 'servings', 'form'],
  'multivitamins': ['brand', 'size', 'servings', 'gender', 'age-group', 'form'],
  'vitamin-a': ['brand', 'dosage', 'servings', 'form', 'source'],
  'vitamin-b': ['brand', 'type', 'dosage', 'servings', 'form', 'complex'],
  'vitamin-c': ['brand', 'dosage', 'servings', 'form', 'buffered', 'time-release'],
  'vitamin-d': ['brand', 'dosage', 'servings', 'form', 'd2-d3', 'source'],
  'vitamin-e': ['brand', 'dosage', 'servings', 'form', 'natural-synthetic'],
  'vitamin-k': ['brand', 'dosage', 'servings', 'form', 'k1-k2'],
  'calcium': ['brand', 'dosage', 'servings', 'form', 'source', 'vitamin-d'],
  'magnesium': ['brand', 'dosage', 'servings', 'form', 'type'],
  'zinc': ['brand', 'dosage', 'servings', 'form', 'chelated'],
  'iron': ['brand', 'dosage', 'servings', 'form', 'gentle', 'vitamin-c'],
  'potassium': ['brand', 'dosage', 'servings', 'form'],
  'omega-3': ['brand', 'dosage', 'servings', 'form', 'epa-dha', 'source'],
  'fish-oil': ['brand', 'dosage', 'servings', 'form', 'epa-dha', 'molecularly-distilled'],
  'krill-oil': ['brand', 'dosage', 'servings', 'form', 'epa-dha', 'astaxanthin'],
  'flaxseed-oil': ['brand', 'dosage', 'servings', 'form', 'organic', 'cold-pressed'],
  'probiotics': ['brand', 'cfu', 'servings', 'strains', 'refrigerated', 'delayed-release'],
  'prebiotics': ['brand', 'dosage', 'servings', 'form', 'fiber-type'],
  'digestive-enzymes': ['brand', 'servings', 'form', 'enzymes-included', 'vegetarian'],
  'fiber-supplements': ['brand', 'dosage', 'servings', 'form', 'fiber-type', 'flavor'],
  'protein-powder': ['brand', 'size', 'servings', 'protein-per-serving', 'source', 'flavor'],
  'whey-protein': ['brand', 'size', 'servings', 'protein-per-serving', 'flavor', 'isolate-concentrate'],
  'plant-protein': ['brand', 'size', 'servings', 'protein-per-serving', 'source', 'flavor'],
  'collagen': ['brand', 'size', 'servings', 'type', 'source', 'form'],
  'amino-acids': ['brand', 'type', 'dosage', 'servings', 'form'],
  'bcaa': ['brand', 'dosage', 'servings', 'ratio', 'flavor', 'form'],
  'creatine': ['brand', 'dosage', 'servings', 'type', 'form', 'flavor'],
  'glucosamine': ['brand', 'dosage', 'servings', 'form', 'chondroitin', 'msm'],
  'turmeric': ['brand', 'dosage', 'servings', 'form', 'curcumin-percentage', 'black-pepper'],
  'ashwagandha': ['brand', 'dosage', 'servings', 'form', 'extract-ratio', 'organic'],
  'elderberry': ['brand', 'dosage', 'servings', 'form', 'extract-ratio', 'organic'],
  'echinacea': ['brand', 'dosage', 'servings', 'form', 'extract-ratio', 'organic'],
  'ginseng': ['brand', 'type', 'dosage', 'servings', 'form', 'extract-ratio'],
  'green-tea-extract': ['brand', 'dosage', 'servings', 'form', 'egcg', 'caffeine'],
  'melatonin': ['brand', 'dosage', 'servings', 'form', 'time-release', 'vegetarian'],
  'coq10': ['brand', 'dosage', 'servings', 'form', 'ubiquinol-ubiquinone'],
  'biotin': ['brand', 'dosage', 'servings', 'form', 'vegetarian'],
  'apple-cider-vinegar': ['brand', 'dosage', 'servings', 'form', 'with-mother', 'organic'],
  'garcinia-cambogia': ['brand', 'dosage', 'servings', 'form', 'hca-percentage'],
  'green-coffee-bean': ['brand', 'dosage', 'servings', 'form', 'chlorogenic-acid'],
  'raspberry-ketones': ['brand', 'dosage', 'servings', 'form'],
  'weight-loss-supplements': ['brand', 'dosage', 'servings', 'form', 'ingredients', 'stimulant-free'],
  'meal-replacements': ['brand', 'servings', 'calories', 'protein', 'flavor', 'form'],
  'greens-powders': ['brand', 'servings', 'ingredients', 'organic', 'flavor'],
  'superfood-blends': ['brand', 'servings', 'ingredients', 'organic', 'form'],
  
  // Herbal & Natural Remedies
  'herbal-remedies': ['brand', 'type', 'dosage', 'servings', 'form', 'organic'],
  'herbal-teas': ['brand', 'type', 'quantity', 'organic', 'caffeine-free', 'bags-loose'],
  'essential-oils': ['brand', 'oil-type', 'size', 'pure', 'organic', 'therapeutic-grade'],
  'aromatherapy': ['brand', 'type', 'size', 'scent', 'pure', 'organic'],
  'cbd-products': ['brand', 'type', 'cbd-content', 'thc-free', 'full-spectrum-isolate', 'organic'],
  'cbd-oil': ['brand', 'cbd-content', 'size', 'thc-free', 'full-spectrum-isolate', 'flavor'],
  'cbd-gummies': ['brand', 'cbd-per-gummy', 'count', 'thc-free', 'flavor', 'vegan'],
  'cbd-topicals': ['brand', 'cbd-content', 'size', 'purpose', 'ingredients'],
  
  // Pain Relief & First Aid
  'pain-relief': ['brand', 'type', 'size', 'active-ingredient', 'strength', 'form'],
  'pain-relievers': ['brand', 'active-ingredient', 'strength', 'count', 'form', 'coated'],
  'topical-pain-relief': ['brand', 'type', 'size', 'active-ingredient', 'strength', 'form'],
  'pain-relief-patches': ['brand', 'active-ingredient', 'count', 'size', 'heat-medicated'],
  'muscle-rubs': ['brand', 'size', 'active-ingredient', 'strength', 'scent'],
  'heating-pads': ['brand', 'size', 'heat-settings', 'auto-shutoff', 'moist-dry', 'electric-microwaveable'],
  'ice-packs': ['brand', 'size', 'reusable', 'gel-ice', 'strap'],
  'hot-cold-therapy': ['brand', 'size', 'reusable', 'microwave-freezer', 'strap'],
  'first-aid-kits': ['brand', 'pieces', 'size', 'case-type', 'purpose'],
  'bandages': ['brand', 'size', 'quantity', 'type', 'waterproof', 'flexible'],
  'gauze': ['brand', 'size', 'quantity', 'sterile', 'type'],
  'medical-tape': ['brand', 'width', 'length', 'type', 'hypoallergenic'],
  'antiseptics': ['brand', 'size', 'active-ingredient', 'form', 'sting-free'],
  'antibiotic-ointment': ['brand', 'size', 'active-ingredient', 'pain-relief'],
  'burn-care': ['brand', 'size', 'type', 'active-ingredient', 'form'],
  'wound-care': ['brand', 'type', 'size', 'quantity', 'waterproof'],
  
  // Digestive Health
  'digestive-health': ['brand', 'type', 'size', 'purpose', 'form'],
  'antacids': ['brand', 'count', 'active-ingredient', 'flavor', 'form'],
  'laxatives': ['brand', 'count', 'type', 'active-ingredient', 'form', 'gentle'],
  'anti-diarrheal': ['brand', 'count', 'active-ingredient', 'form'],
  'gas-relief': ['brand', 'count', 'active-ingredient', 'form', 'extra-strength'],
  'nausea-relief': ['brand', 'count', 'active-ingredient', 'form'],
  'heartburn-relief': ['brand', 'count', 'active-ingredient', 'form', 'strength'],

  // Cold, Flu & Allergy
  'cold-flu-allergy': ['brand', 'type', 'size', 'active-ingredient', 'form'],
  'cold-medicine': ['brand', 'count', 'symptoms', 'active-ingredient', 'form', 'day-night'],
  'cough-medicine': ['brand', 'size', 'type', 'active-ingredient', 'form', 'sugar-free'],
  'cough-drops': ['brand', 'count', 'flavor', 'menthol', 'sugar-free'],
  'throat-lozenges': ['brand', 'count', 'flavor', 'active-ingredient', 'sugar-free'],
  'nasal-spray': ['brand', 'size', 'type', 'active-ingredient', 'saline-medicated'],
  'decongestants': ['brand', 'count', 'active-ingredient', 'form', 'non-drowsy'],
  'allergy-medicine': ['brand', 'count', 'active-ingredient', 'form', 'non-drowsy', '24-hour'],
  'antihistamines': ['brand', 'count', 'active-ingredient', 'form', 'non-drowsy'],
  'sinus-medicine': ['brand', 'count', 'symptoms', 'active-ingredient', 'form'],
  'flu-medicine': ['brand', 'count', 'symptoms', 'active-ingredient', 'form', 'day-night'],
  'immune-support': ['brand', 'servings', 'ingredients', 'form', 'vitamin-c'],
  
  // Sleep & Relaxation
  'sleep-aids': ['brand', 'count', 'active-ingredient', 'form', 'non-habit-forming'],
  'sleep-supplements': ['brand', 'servings', 'ingredients', 'form', 'melatonin'],
  'stress-relief': ['brand', 'servings', 'ingredients', 'form', 'natural'],
  'calming-supplements': ['brand', 'servings', 'ingredients', 'form', 'non-drowsy'],
  'sleep-masks': ['brand', 'material', 'adjustable', 'contoured', 'light-blocking'],
  'white-noise-machines': ['brand', 'sounds', 'timer', 'volume-control', 'night-light'],
  'aromatherapy-diffusers': ['brand', 'capacity', 'runtime', 'led-lights', 'auto-shutoff'],
  
  // Medical Devices & Equipment
  'medical-devices': ['brand', 'type', 'size', 'accuracy', 'warranty'],
  'blood-pressure-monitors': ['brand', 'type', 'cuff-size', 'memory', 'irregular-heartbeat', 'app-sync'],
  'thermometers': ['brand', 'type', 'age-group', 'speed', 'memory', 'fever-alarm'],
  'pulse-oximeters': ['brand', 'display-type', 'accuracy', 'battery-type', 'alarm'],
  'glucose-meters': ['brand', 'strips-included', 'memory', 'app-sync', 'no-coding'],
  'nebulizers': ['brand', 'type', 'compressor-mesh', 'noise-level', 'accessories'],
  'cpap-machines': ['brand', 'type', 'pressure-range', 'humidifier', 'data-tracking', 'mask-included'],
  'tens-units': ['brand', 'channels', 'modes', 'intensity-levels', 'pads-included', 'rechargeable'],
  'stethoscopes': ['brand', 'type', 'tubing-length', 'dual-single-head', 'pediatric-adult'],
  'otoscopes': ['brand', 'type', 'light-source', 'specula-included', 'magnification'],
  'peak-flow-meters': ['brand', 'range', 'age-group', 'zones'],
  'pill-organizers': ['brand', 'compartments', 'days', 'times-per-day', 'size'],
  'pill-cutters': ['brand', 'size', 'blade-type', 'storage', 'safety'],
  'pill-crushers': ['brand', 'type', 'capacity', 'storage', 'easy-grip'],
  'medicine-cups': ['brand', 'capacity', 'material', 'measurements', 'quantity'],
  'syringes': ['brand', 'size', 'quantity', 'type', 'sterile'],
  'lancets': ['brand', 'gauge', 'quantity', 'sterile', 'compatibility'],

  // Mobility & Accessibility
  'mobility-aids': ['brand', 'type', 'weight-capacity', 'adjustable', 'foldable'],
  'canes': ['brand', 'type', 'height-adjustable', 'weight-capacity', 'tip-type', 'handle-type'],
  'walking-sticks': ['brand', 'material', 'height-adjustable', 'weight-capacity', 'tip'],
  'crutches': ['brand', 'type', 'height-adjustable', 'weight-capacity', 'underarm-forearm'],
  'walkers': ['brand', 'type', 'weight-capacity', 'wheels', 'seat', 'foldable'],
  'rollators': ['brand', 'wheels', 'weight-capacity', 'seat', 'basket', 'brakes'],
  'wheelchairs': ['brand', 'type', 'weight-capacity', 'seat-width', 'foldable', 'self-propelled'],
  'transport-chairs': ['brand', 'weight-capacity', 'seat-width', 'foldable', 'footrests'],
  'knee-scooters': ['brand', 'weight-capacity', 'adjustable-height', 'foldable', 'basket'],
  'shower-chairs': ['brand', 'weight-capacity', 'adjustable-height', 'back-support', 'armrests'],
  'bath-benches': ['brand', 'weight-capacity', 'adjustable-height', 'back-support', 'non-slip'],
  'toilet-safety-rails': ['brand', 'weight-capacity', 'adjustable-width', 'padded', 'foldable'],
  'raised-toilet-seats': ['brand', 'height', 'weight-capacity', 'armrests', 'lid'],
  'grab-bars': ['brand', 'length', 'weight-capacity', 'material', 'mounting-type', 'finish'],
  'bed-rails': ['brand', 'length', 'height', 'weight-capacity', 'foldable', 'pockets'],
  'bed-assist-handles': ['brand', 'type', 'weight-capacity', 'adjustable', 'pockets'],
  'transfer-benches': ['brand', 'weight-capacity', 'adjustable-height', 'back-support', 'reversible'],
  'lift-chairs': ['brand', 'size', 'weight-capacity', 'positions', 'heat-massage', 'power-source'],
  'stair-lifts': ['brand', 'type', 'weight-capacity', 'track-length', 'swivel-seat', 'battery-backup'],
  'patient-lifts': ['brand', 'type', 'weight-capacity', 'sling-included', 'electric-manual'],
  
  // Orthopedic & Support
  'orthopedic-support': ['brand', 'type', 'size', 'material', 'adjustable'],
  'back-braces': ['brand', 'size', 'support-level', 'adjustable', 'breathable'],
  'lumbar-supports': ['brand', 'size', 'material', 'adjustable', 'heat'],
  'posture-correctors': ['brand', 'size', 'adjustable', 'discreet', 'breathable'],
  'knee-braces': ['brand', 'size', 'support-level', 'adjustable', 'open-closed-patella'],
  'ankle-braces': ['brand', 'size', 'support-level', 'adjustable', 'lace-up-strap'],
  'wrist-braces': ['brand', 'size', 'support-level', 'adjustable', 'splint', 'left-right'],
  'elbow-braces': ['brand', 'size', 'support-level', 'adjustable', 'compression'],
  'shoulder-braces': ['brand', 'size', 'support-level', 'adjustable', 'immobilizer-support'],
  'neck-braces': ['brand', 'size', 'support-level', 'adjustable', 'soft-rigid'],
  'compression-sleeves': ['brand', 'size', 'body-part', 'compression-level', 'material'],
  'compression-socks': ['brand', 'size', 'compression-level', 'length', 'open-closed-toe'],
  'compression-stockings': ['brand', 'size', 'compression-level', 'length', 'open-closed-toe'],
  'orthopedic-pillows': ['brand', 'type', 'size', 'material', 'memory-foam', 'washable-cover'],
  'cervical-pillows': ['brand', 'size', 'material', 'contour', 'memory-foam'],
  'wedge-pillows': ['brand', 'size', 'angle', 'material', 'memory-foam', 'washable-cover'],
  'seat-cushions': ['brand', 'size', 'material', 'memory-foam', 'coccyx-cutout', 'non-slip'],
  'lumbar-cushions': ['brand', 'size', 'material', 'memory-foam', 'adjustable-strap'],

  // Incontinence Care
  'incontinence-care': ['brand', 'type', 'size', 'absorbency', 'gender'],
  'adult-diapers': ['brand', 'size', 'absorbency', 'count', 'gender', 'pull-up-tab'],
  'incontinence-pads': ['brand', 'size', 'absorbency', 'count', 'gender', 'adhesive'],
  'incontinence-underwear': ['brand', 'size', 'absorbency', 'count', 'gender', 'disposable-reusable'],
  'bed-pads': ['brand', 'size', 'absorbency', 'count', 'disposable-reusable', 'waterproof'],
  'mattress-protectors': ['brand', 'size', 'waterproof', 'breathable', 'hypoallergenic'],
  
  // Diabetes Care
  'diabetes-care': ['brand', 'type', 'size', 'compatibility', 'quantity'],
  'glucose-test-strips': ['brand', 'quantity', 'compatibility', 'expiration'],
  'insulin-syringes': ['brand', 'size', 'gauge', 'quantity', 'sterile'],
  'insulin-pen-needles': ['brand', 'length', 'gauge', 'quantity', 'compatibility'],
  'diabetic-socks': ['brand', 'size', 'material', 'non-binding', 'seamless'],
  'diabetic-shoes': ['brand', 'size', 'width', 'material', 'therapeutic', 'removable-insoles'],
  'lancet-devices': ['brand', 'depth-settings', 'lancets-included', 'easy-load'],
  'sharps-containers': ['brand', 'capacity', 'size', 'locking-lid', 'wall-mount'],
  
  // Vision Care
  'vision-care': ['brand', 'type', 'size', 'purpose'],
  'reading-glasses': ['brand', 'strength', 'frame-style', 'lens-type', 'gender'],
  'blue-light-glasses': ['brand', 'frame-style', 'lens-type', 'prescription-non-prescription'],
  'safety-glasses': ['brand', 'lens-type', 'uv-protection', 'anti-fog', 'prescription-compatible'],
  'eyeglass-cases': ['brand', 'size', 'material', 'hard-soft', 'closure-type'],
  'eyeglass-cleaners': ['brand', 'size', 'type', 'spray-wipes', 'anti-fog'],
  'contact-lens-solution': ['brand', 'size', 'type', 'multi-purpose-peroxide', 'no-rub'],
  'contact-lens-cases': ['brand', 'type', 'material', 'color', 'mirror'],
  'eye-drops': ['brand', 'size', 'purpose', 'preservative-free', 'single-use-bottle'],
  'artificial-tears': ['brand', 'size', 'preservative-free', 'gel-drops', 'single-use'],
  'eye-vitamins': ['brand', 'servings', 'ingredients', 'form', 'lutein-zeaxanthin'],
  'magnifiers': ['brand', 'magnification', 'type', 'led-light', 'handheld-standing'],
  
  // Hearing Care
  'hearing-care': ['brand', 'type', 'size', 'features'],
  'hearing-aids': ['brand', 'type', 'battery-type', 'rechargeable', 'bluetooth', 'app-control'],
  'hearing-aid-batteries': ['brand', 'size', 'quantity', 'zinc-air', 'mercury-free'],
  'hearing-amplifiers': ['brand', 'type', 'battery-type', 'volume-control', 'rechargeable'],
  'ear-plugs': ['brand', 'type', 'nrr-rating', 'quantity', 'reusable-disposable'],
  'ear-wax-removal': ['brand', 'type', 'size', 'drops-irrigation', 'safe'],
  
  // Respiratory Care
  'respiratory-care': ['brand', 'type', 'size', 'purpose'],
  'oxygen-concentrators': ['brand', 'flow-rate', 'weight', 'portable-stationary', 'battery-life'],
  'oxygen-tanks': ['brand', 'capacity', 'type', 'regulator-included', 'portable'],
  'cpap-supplies': ['brand', 'type', 'size', 'compatibility', 'disposable-reusable'],
  'cpap-masks': ['brand', 'type', 'size', 'full-face-nasal', 'headgear-included'],
  'cpap-filters': ['brand', 'type', 'quantity', 'compatibility', 'disposable-reusable'],
  'humidifier-chambers': ['brand', 'capacity', 'compatibility', 'dishwasher-safe'],
  'breathing-exercisers': ['brand', 'type', 'resistance-levels', 'indicator', 'mouthpiece'],
  'steam-inhalers': ['brand', 'capacity', 'type', 'timer', 'mask-included'],

  // Women's Health
  'womens-health': ['brand', 'type', 'size', 'purpose', 'quantity'],
  'prenatal-vitamins': ['brand', 'servings', 'folic-acid', 'dha', 'form'],
  'pregnancy-tests': ['brand', 'quantity', 'sensitivity', 'digital-line', 'early-detection'],
  'ovulation-tests': ['brand', 'quantity', 'sensitivity', 'digital-line'],
  'fertility-supplements': ['brand', 'servings', 'ingredients', 'form', 'gender'],
  'menopause-support': ['brand', 'servings', 'ingredients', 'form', 'hormone-free'],
  'feminine-hygiene': ['brand', 'type', 'size', 'quantity', 'scented-unscented'],
  'menstrual-cups': ['brand', 'size', 'capacity', 'material', 'reusable'],
  'period-underwear': ['brand', 'size', 'absorbency', 'style', 'reusable'],
  'breast-pumps': ['brand', 'type', 'suction-levels', 'battery-electric', 'double-single'],
  'nursing-pads': ['brand', 'quantity', 'absorbency', 'disposable-reusable', 'contoured'],
  'nipple-cream': ['brand', 'size', 'ingredients', 'lanolin-free', 'organic'],
  'kegel-exercisers': ['brand', 'type', 'material', 'app-connected', 'resistance-levels'],
  'maternity-support-belts': ['brand', 'size', 'adjustable', 'breathable', 'back-support'],
  
  // Men's Health
  'mens-health': ['brand', 'type', 'size', 'purpose', 'servings'],
  'prostate-supplements': ['brand', 'servings', 'ingredients', 'form', 'saw-palmetto'],
  'testosterone-boosters': ['brand', 'servings', 'ingredients', 'form', 'natural'],
  'male-enhancement': ['brand', 'servings', 'ingredients', 'form', 'natural'],
  'hair-growth-supplements': ['brand', 'servings', 'ingredients', 'form', 'biotin'],
  
  // Sexual Health
  'sexual-health': ['brand', 'type', 'size', 'quantity', 'material'],
  'condoms': ['brand', 'quantity', 'size', 'material', 'lubricated', 'textured'],
  'lubricants': ['brand', 'size', 'type', 'water-silicone-oil', 'flavor', 'warming-cooling'],
  'fertility-lubricants': ['brand', 'size', 'ph-balanced', 'sperm-friendly'],
  
  // Dental Care
  'dental-care': ['brand', 'type', 'size', 'flavor', 'purpose'],
  'toothpaste': ['brand', 'size', 'flavor', 'whitening', 'fluoride', 'sensitivity'],
  'toothbrushes': ['brand', 'type', 'bristle-softness', 'head-size', 'manual-electric'],
  'electric-toothbrushes': ['brand', 'type', 'modes', 'timer', 'pressure-sensor', 'battery-life'],
  'replacement-brush-heads': ['brand', 'quantity', 'compatibility', 'bristle-type'],
  'mouthwash': ['brand', 'size', 'flavor', 'alcohol-free', 'whitening', 'fluoride'],
  'dental-floss': ['brand', 'length', 'flavor', 'waxed-unwaxed', 'tape-string'],
  'floss-picks': ['brand', 'quantity', 'flavor', 'angled', 'handle-type'],
  'interdental-brushes': ['brand', 'size', 'quantity', 'angled', 'handle-type'],
  'tongue-scrapers': ['brand', 'material', 'quantity', 'handle-type'],
  'teeth-whitening-strips': ['brand', 'treatments', 'duration', 'sensitivity', 'professional-strength'],
  'teeth-whitening-kits': ['brand', 'treatments', 'led-light', 'gel-included', 'sensitivity'],
  'whitening-toothpaste': ['brand', 'size', 'flavor', 'peroxide', 'sensitivity'],
  'denture-cleaners': ['brand', 'quantity', 'type', 'tablets-liquid', 'overnight'],
  'denture-adhesive': ['brand', 'size', 'type', 'hold-time', 'flavor'],
  'mouth-guards': ['brand', 'type', 'size', 'purpose', 'boil-bite-custom'],
  'night-guards': ['brand', 'size', 'material', 'upper-lower', 'moldable'],

  // Foot Care
  'foot-care': ['brand', 'type', 'size', 'purpose', 'quantity'],
  'foot-massagers': ['brand', 'type', 'heat', 'intensity-levels', 'shiatsu', 'water'],
  'foot-baths': ['brand', 'capacity', 'heat', 'massage', 'bubbles', 'pedicure-attachments'],
  'insoles': ['brand', 'size', 'type', 'arch-support', 'cushioning', 'purpose'],
  'orthotic-inserts': ['brand', 'size', 'arch-type', 'material', 'full-length-3-4'],
  'heel-cups': ['brand', 'size', 'material', 'cushioning', 'pair'],
  'arch-supports': ['brand', 'size', 'arch-type', 'material', 'adhesive-strap'],
  'toe-separators': ['brand', 'size', 'material', 'quantity', 'gel-foam'],
  'bunion-correctors': ['brand', 'size', 'type', 'material', 'day-night'],
  'corn-removers': ['brand', 'quantity', 'type', 'medicated', 'cushioned'],
  'callus-removers': ['brand', 'type', 'material', 'electric-manual', 'replacement-heads'],
  'foot-files': ['brand', 'type', 'material', 'coarse-fine', 'handle'],
  'toenail-clippers': ['brand', 'size', 'material', 'straight-curved', 'file-included'],
  'antifungal-treatments': ['brand', 'size', 'type', 'active-ingredient', 'cream-spray-liquid'],
  'athletes-foot-treatment': ['brand', 'size', 'type', 'active-ingredient', 'form'],
  'foot-powder': ['brand', 'size', 'purpose', 'antifungal', 'odor-control'],
  'foot-cream': ['brand', 'size', 'purpose', 'ingredients', 'cracked-heels'],
  
  // Massage & Therapy
  'massage-therapy': ['brand', 'type', 'power-source', 'heat', 'intensity-levels'],
  'massage-chairs': ['brand', 'type', 'massage-techniques', 'heat', 'zero-gravity', 'airbags'],
  'massage-cushions': ['brand', 'type', 'heat', 'massage-nodes', 'vibration', 'power-source'],
  'back-massagers': ['brand', 'type', 'power-source', 'heat', 'intensity-levels', 'handheld-pillow'],
  'neck-massagers': ['brand', 'type', 'power-source', 'heat', 'intensity-levels', 'shiatsu'],
  'handheld-massagers': ['brand', 'type', 'power-source', 'attachments', 'intensity-levels', 'cordless'],
  'percussion-massagers': ['brand', 'attachments', 'speed-levels', 'battery-life', 'noise-level'],
  'massage-guns': ['brand', 'attachments', 'speed-levels', 'battery-life', 'amplitude', 'quiet'],
  'massage-balls': ['brand', 'size', 'material', 'texture', 'vibrating'],
  'massage-rollers': ['brand', 'type', 'size', 'material', 'texture', 'vibrating'],
  'acupressure-mats': ['brand', 'size', 'spikes', 'pillow-included', 'material'],
  'foam-rollers': ['brand', 'length', 'diameter', 'density', 'texture', 'vibrating'],
  'massage-oils': ['brand', 'size', 'scent', 'ingredients', 'organic', 'warming'],
  'massage-lotions': ['brand', 'size', 'scent', 'ingredients', 'non-greasy', 'pump'],
  
  // Alternative Medicine
  'alternative-medicine': ['brand', 'type', 'size', 'purpose', 'natural'],
  'acupuncture-supplies': ['brand', 'type', 'size', 'quantity', 'sterile'],
  'cupping-sets': ['brand', 'cups', 'size', 'material', 'pump-included', 'silicone-glass'],
  'gua-sha-tools': ['brand', 'material', 'shape', 'size', 'jade-rose-quartz'],
  'jade-rollers': ['brand', 'material', 'size', 'dual-ended', 'cooling'],
  'crystal-healing': ['brand', 'crystal-type', 'size', 'shape', 'natural'],
  'himalayan-salt-lamps': ['brand', 'weight', 'size', 'bulb-included', 'dimmer'],
  'meditation-cushions': ['brand', 'size', 'material', 'height', 'washable-cover'],
  'yoga-props': ['brand', 'type', 'size', 'material', 'purpose'],
  'singing-bowls': ['brand', 'size', 'material', 'note', 'mallet-included'],
  'tuning-forks': ['brand', 'frequency', 'material', 'weighted-unweighted', 'activator'],
};
