/**
 * Pet Supplies Category Attribute Mappings
 * 
 * Comprehensive mappings for pet products and accessories
 */

export const petSuppliesMappings = {
  // Main Pet Supplies
  'pet-supplies': ['brand', 'pet-type', 'size', 'color', 'material'],
  'pets': ['brand', 'pet-type', 'size', 'age-group'],
  
  // Dog Supplies
  'dog-supplies': ['brand', 'size', 'color', 'breed-size', 'material'],
  'dog-food': ['brand', 'size', 'age-group', 'breed-size', 'dry-wet', 'grain-free', 'protein-source'],
  'dog-treats': ['brand', 'size', 'flavor', 'training-dental', 'grain-free', 'age-group'],
  'dog-toys': ['brand', 'type', 'size', 'material', 'squeaky', 'durability'],
  'dog-beds': ['brand', 'size', 'material', 'washable', 'orthopedic', 'shape'],
  'dog-crates': ['brand', 'size', 'material', 'doors', 'foldable', 'divider'],
  'dog-collars': ['brand', 'size', 'material', 'adjustable', 'reflective', 'buckle-type'],
  'dog-leashes': ['brand', 'length', 'material', 'width', 'retractable', 'reflective'],
  'dog-harnesses': ['brand', 'size', 'material', 'adjustable', 'no-pull', 'reflective'],
  'dog-bowls': ['brand', 'capacity', 'material', 'elevated', 'non-slip', 'slow-feeder'],
  'dog-grooming': ['brand', 'type', 'size', 'cordless', 'attachments'],
  'dog-shampoo': ['brand', 'size', 'scent', 'hypoallergenic', 'medicated', 'puppy-adult'],
  'dog-brushes': ['brand', 'type', 'bristle-type', 'size', 'self-cleaning'],
  'dog-nail-clippers': ['brand', 'type', 'size', 'safety-guard', 'led-light'],
  'dog-clippers': ['brand', 'cordless', 'blade-sizes', 'quiet', 'attachments'],
  'dog-clothing': ['brand', 'size', 'type', 'season', 'waterproof', 'reflective'],
  'dog-boots': ['brand', 'size', 'material', 'waterproof', 'anti-slip', 'set-size'],
  'dog-carriers': ['brand', 'size', 'material', 'airline-approved', 'ventilation', 'weight-capacity'],
  'dog-car-seats': ['brand', 'size', 'weight-capacity', 'safety-tether', 'washable'],
  'dog-seat-covers': ['brand', 'size', 'material', 'waterproof', 'hammock-style', 'non-slip'],
  'dog-gates': ['brand', 'width-range', 'height', 'pressure-hardware', 'walk-through'],
  'dog-doors': ['brand', 'size', 'material', 'flap-type', 'locking', 'weatherproof'],
  'dog-houses': ['brand', 'size', 'material', 'insulated', 'elevated', 'weatherproof'],
  'dog-pens': ['brand', 'size', 'height', 'panels', 'material', 'indoor-outdoor'],
  'dog-training-pads': ['brand', 'size', 'count', 'absorbency', 'scented', 'adhesive'],
  'dog-waste-bags': ['brand', 'count', 'scented', 'biodegradable', 'dispenser-included'],
  'dog-poop-scoopers': ['brand', 'type', 'material', 'handle-length', 'rake-included'],
  'dog-training-aids': ['brand', 'type', 'size', 'purpose'],
  'dog-clickers': ['brand', 'type', 'wrist-strap', 'volume'],
  'dog-whistles': ['brand', 'type', 'frequency', 'adjustable', 'lanyard'],
  'dog-muzzles': ['brand', 'size', 'material', 'breathable', 'basket-soft'],
  'dog-life-jackets': ['brand', 'size', 'weight-range', 'handle', 'reflective', 'buoyancy'],
  'dog-cooling-mats': ['brand', 'size', 'material', 'self-cooling', 'washable'],
  'dog-heating-pads': ['brand', 'size', 'temperature-settings', 'auto-shutoff', 'chew-resistant'],
  'dog-water-fountains': ['brand', 'capacity', 'material', 'filter-included', 'quiet', 'pump-type'],
  'dog-feeders': ['brand', 'capacity', 'type', 'programmable', 'portions', 'battery-plug'],
  'dog-id-tags': ['brand', 'material', 'shape', 'engraving', 'silent'],
  'dog-gps-trackers': ['brand', 'subscription', 'battery-life', 'range', 'waterproof'],
  
  // Cat Supplies
  'cat-supplies': ['brand', 'size', 'color', 'material'],
  'cat-food': ['brand', 'size', 'age-group', 'dry-wet', 'grain-free', 'protein-source', 'indoor-outdoor'],
  'cat-treats': ['brand', 'size', 'flavor', 'dental', 'grain-free', 'age-group'],
  'cat-toys': ['brand', 'type', 'material', 'interactive', 'catnip', 'battery-required'],
  'cat-beds': ['brand', 'size', 'material', 'washable', 'heated', 'shape'],
  'cat-trees': ['brand', 'height', 'levels', 'scratching-posts', 'weight-capacity', 'material'],
  'cat-scratchers': ['brand', 'type', 'size', 'material', 'catnip-included', 'wall-floor'],
  'cat-collars': ['brand', 'size', 'material', 'breakaway', 'bell', 'reflective'],
  'cat-harnesses': ['brand', 'size', 'material', 'escape-proof', 'adjustable', 'vest-strap'],
  'cat-leashes': ['brand', 'length', 'material', 'width', 'retractable'],
  'cat-bowls': ['brand', 'capacity', 'material', 'elevated', 'non-slip', 'whisker-friendly'],
  'cat-litter': ['brand', 'weight', 'type', 'clumping', 'scented-unscented', 'dust-free'],
  'litter-boxes': ['brand', 'size', 'type', 'covered', 'self-cleaning', 'entry-type'],
  'litter-mats': ['brand', 'size', 'material', 'trapping-efficiency', 'washable'],
  'litter-scoops': ['brand', 'material', 'size', 'slotted', 'handle-length'],
  'cat-grooming': ['brand', 'type', 'size', 'self-cleaning'],
  'cat-brushes': ['brand', 'type', 'bristle-type', 'self-cleaning', 'size'],
  'cat-nail-clippers': ['brand', 'type', 'size', 'safety-guard', 'led-light'],
  'cat-shampoo': ['brand', 'size', 'scent', 'hypoallergenic', 'waterless', 'kitten-adult'],
  'cat-carriers': ['brand', 'size', 'material', 'airline-approved', 'ventilation', 'top-loading'],
  'cat-doors': ['brand', 'size', 'material', 'flap-type', 'locking', 'weatherproof'],
  'cat-houses': ['brand', 'size', 'material', 'insulated', 'indoor-outdoor', 'weatherproof'],
  'cat-tunnels': ['brand', 'length', 'diameter', 'material', 'collapsible', 'crinkle'],
  'cat-water-fountains': ['brand', 'capacity', 'material', 'filter-included', 'quiet', 'led-light'],
  'cat-feeders': ['brand', 'capacity', 'type', 'programmable', 'portions', 'battery-plug'],
  'cat-id-tags': ['brand', 'material', 'shape', 'engraving', 'silent'],
  'cat-gps-trackers': ['brand', 'subscription', 'battery-life', 'range', 'waterproof'],
  'cat-furniture': ['brand', 'type', 'size', 'material', 'weight-capacity'],
  'cat-shelves': ['brand', 'size', 'weight-capacity', 'material', 'mounting-type'],
  'cat-window-perches': ['brand', 'size', 'weight-capacity', 'suction-cups', 'cushioned'],
  'cat-calming': ['brand', 'type', 'size', 'duration', 'pheromone-herbal'],
  
  // Small Animal Supplies
  'small-animal-supplies': ['brand', 'pet-type', 'size', 'material'],
  'small-animal-food': ['brand', 'pet-type', 'size', 'age-group', 'pellets-mix'],
  'small-animal-treats': ['brand', 'pet-type', 'size', 'flavor', 'natural'],
  'small-animal-cages': ['brand', 'size', 'material', 'levels', 'bar-spacing', 'accessories-included'],
  'hamster-cages': ['brand', 'size', 'material', 'levels', 'tubes-included', 'wheel-included'],
  'guinea-pig-cages': ['brand', 'size', 'material', 'expandable', 'ramp-included'],
  'rabbit-cages': ['brand', 'size', 'material', 'indoor-outdoor', 'run-included'],
  'small-animal-bedding': ['brand', 'volume', 'material', 'dust-free', 'absorbency', 'scented'],
  'small-animal-toys': ['brand', 'pet-type', 'type', 'material', 'chewable'],
  'exercise-wheels': ['brand', 'diameter', 'material', 'silent', 'stand-attach'],
  'exercise-balls': ['brand', 'diameter', 'material', 'ventilation', 'pet-type'],
  'small-animal-hideouts': ['brand', 'size', 'material', 'pet-type', 'chewable'],
  'small-animal-bowls': ['brand', 'capacity', 'material', 'tip-proof', 'chew-proof'],
  'water-bottles': ['brand', 'capacity', 'material', 'leak-proof', 'ball-bearing', 'chew-guard'],
  'hay-feeders': ['brand', 'size', 'material', 'mounting-type', 'capacity'],
  'small-animal-carriers': ['brand', 'size', 'material', 'ventilation', 'handle-type'],
  'small-animal-harnesses': ['brand', 'pet-type', 'size', 'material', 'adjustable', 'leash-included'],
  
  // Bird Supplies
  'bird-supplies': ['brand', 'bird-type', 'size', 'material'],
  'bird-food': ['brand', 'bird-type', 'size', 'seed-pellet', 'fortified'],
  'bird-treats': ['brand', 'bird-type', 'size', 'flavor', 'type'],
  'bird-cages': ['brand', 'size', 'material', 'bar-spacing', 'shape', 'stand-included'],
  'bird-perches': ['brand', 'length', 'diameter', 'material', 'natural-rope'],
  'bird-toys': ['brand', 'type', 'size', 'material', 'interactive', 'bell'],
  'bird-swings': ['brand', 'size', 'material', 'bell', 'beads'],
  'bird-ladders': ['brand', 'length', 'material', 'rungs'],
  'bird-mirrors': ['brand', 'size', 'material', 'bell', 'mounting'],
  'bird-baths': ['brand', 'size', 'material', 'hanging-standing', 'depth'],
  'bird-feeders': ['brand', 'capacity', 'material', 'type', 'mounting'],
  'bird-waterers': ['brand', 'capacity', 'material', 'type', 'leak-proof'],
  'bird-nests': ['brand', 'size', 'material', 'bird-type', 'mounting'],
  'nesting-material': ['brand', 'type', 'size', 'natural-synthetic'],
  'bird-carriers': ['brand', 'size', 'material', 'ventilation', 'perch-included'],
  'bird-cage-covers': ['brand', 'size', 'material', 'light-blocking', 'breathable'],
  'cuttlebones': ['brand', 'size', 'quantity', 'holder-included'],
  'mineral-blocks': ['brand', 'size', 'flavor', 'holder-included'],
  
  // Fish & Aquarium Supplies
  'fish-aquarium': ['brand', 'size', 'type', 'material'],
  'fish-food': ['brand', 'fish-type', 'size', 'form', 'floating-sinking', 'color-enhancing'],
  'aquariums': ['brand', 'capacity', 'shape', 'material', 'kit-tank-only'],
  'fish-tanks': ['brand', 'capacity', 'shape', 'material', 'rimless', 'stand-included'],
  'aquarium-filters': ['brand', 'type', 'flow-rate', 'tank-size', 'media-included'],
  'aquarium-heaters': ['brand', 'wattage', 'tank-size', 'adjustable', 'submersible'],
  'aquarium-lights': ['brand', 'length', 'type', 'spectrum', 'timer', 'adjustable'],
  'aquarium-pumps': ['brand', 'flow-rate', 'type', 'adjustable', 'quiet'],
  'air-stones': ['brand', 'size', 'shape', 'material', 'bubble-size'],
  'aquarium-decorations': ['brand', 'type', 'size', 'material', 'safe-for-fish'],
  'aquarium-plants': ['brand', 'type', 'size', 'live-artificial', 'difficulty'],
  'aquarium-substrate': ['brand', 'type', 'weight', 'color', 'grain-size'],
  'aquarium-gravel': ['brand', 'weight', 'color', 'size', 'coated'],
  'aquarium-sand': ['brand', 'weight', 'color', 'grain-size', 'natural-colored'],
  'aquarium-backgrounds': ['brand', 'size', 'design', 'material', 'adhesive-static'],
  'fish-nets': ['brand', 'size', 'material', 'fine-coarse', 'handle-length'],
  'aquarium-test-kits': ['brand', 'parameters', 'tests-included', 'strips-liquid'],
  'water-conditioners': ['brand', 'size', 'purpose', 'treats-gallons'],
  'aquarium-cleaners': ['brand', 'type', 'size', 'purpose'],
  'gravel-vacuums': ['brand', 'length', 'diameter', 'self-priming', 'flow-control'],
  'algae-scrapers': ['brand', 'type', 'blade-material', 'handle-length', 'magnetic'],
  'fish-breeding': ['brand', 'type', 'size', 'material', 'purpose'],
  'aquarium-dividers': ['brand', 'size', 'material', 'holes-size', 'adjustable'],
  
  // Reptile & Amphibian Supplies
  'reptile-supplies': ['brand', 'reptile-type', 'size', 'material'],
  'reptile-food': ['brand', 'reptile-type', 'size', 'live-frozen-pellet', 'age-group'],
  'reptile-terrariums': ['brand', 'size', 'material', 'front-opening', 'screen-top'],
  'reptile-heating': ['brand', 'type', 'wattage', 'size', 'thermostat'],
  'heat-lamps': ['brand', 'wattage', 'bulb-type', 'fixture-included', 'clamp'],
  'heat-mats': ['brand', 'wattage', 'size', 'adhesive', 'thermostat-compatible'],
  'heat-cables': ['brand', 'wattage', 'length', 'waterproof', 'thermostat-compatible'],
  'reptile-lighting': ['brand', 'type', 'wattage', 'uvb-percentage', 'bulb-fixture'],
  'uvb-bulbs': ['brand', 'wattage', 'uvb-percentage', 'type', 'lifespan'],
  'reptile-substrate': ['brand', 'type', 'volume', 'reptile-type', 'humidity-retention'],
  'reptile-decorations': ['brand', 'type', 'size', 'material', 'naturalistic'],
  'reptile-hides': ['brand', 'size', 'material', 'humid-dry', 'reptile-type'],
  'reptile-water-dishes': ['brand', 'size', 'material', 'tip-proof', 'rock-style'],
  'reptile-food-dishes': ['brand', 'size', 'material', 'tip-proof', 'escape-proof'],
  'reptile-thermometers': ['brand', 'type', 'digital-analog', 'probe', 'hygrometer'],
  'reptile-misters': ['brand', 'type', 'capacity', 'programmable', 'nozzles'],
  'reptile-foggers': ['brand', 'capacity', 'runtime', 'adjustable', 'quiet'],
  
  // Pet Health & Wellness
  'pet-health-wellness': ['brand', 'pet-type', 'size', 'purpose'],
  'flea-tick-prevention': ['brand', 'pet-type', 'weight-range', 'duration', 'topical-oral'],
  'heartworm-prevention': ['brand', 'pet-type', 'weight-range', 'duration', 'chewable-topical'],
  'pet-vitamins': ['brand', 'pet-type', 'purpose', 'count', 'chewable-tablet'],
  'joint-supplements': ['brand', 'pet-type', 'count', 'glucosamine', 'chewable-powder'],
  'probiotics': ['brand', 'pet-type', 'count', 'cfu', 'powder-chewable'],
  'omega-supplements': ['brand', 'pet-type', 'count', 'source', 'liquid-chewable'],
  'calming-supplements': ['brand', 'pet-type', 'count', 'ingredients', 'chewable-liquid'],
  'dental-care': ['brand', 'pet-type', 'type', 'flavor', 'enzymatic'],
  'pet-toothbrushes': ['brand', 'pet-type', 'size', 'finger-handle', 'bristle-type'],
  'pet-toothpaste': ['brand', 'pet-type', 'size', 'flavor', 'enzymatic'],
  'dental-chews': ['brand', 'pet-type', 'size', 'count', 'flavor', 'tartar-control'],
  'ear-cleaners': ['brand', 'pet-type', 'size', 'medicated', 'wipes-liquid'],
  'eye-care': ['brand', 'pet-type', 'size', 'purpose', 'wipes-drops'],
  'paw-care': ['brand', 'pet-type', 'size', 'purpose', 'balm-wipes'],
  'first-aid-kits': ['brand', 'pet-type', 'pieces', 'case-type'],
  'pet-medications': ['brand', 'pet-type', 'purpose', 'size', 'prescription-otc'],
  'wound-care': ['brand', 'type', 'size', 'antiseptic', 'bandages-spray'],
  'pet-thermometers': ['brand', 'type', 'digital-analog', 'rectal-ear'],
  'pill-dispensers': ['brand', 'type', 'size', 'soft-treat'],
  'e-collars': ['brand', 'size', 'material', 'clear-opaque', 'adjustable'],
  'recovery-suits': ['brand', 'size', 'material', 'purpose', 'washable'],
  
  // Pet Travel & Outdoor
  'pet-travel-outdoor': ['brand', 'pet-type', 'size', 'material'],
  'pet-strollers': ['brand', 'weight-capacity', 'wheels', 'foldable', 'storage', 'weather-cover'],
  'pet-backpacks': ['brand', 'weight-capacity', 'size', 'ventilation', 'airline-approved'],
  'travel-bowls': ['brand', 'capacity', 'material', 'collapsible', 'leak-proof'],
  'travel-water-bottles': ['brand', 'capacity', 'material', 'dispenser-type', 'leak-proof'],
  'pet-seat-belts': ['brand', 'size', 'adjustable', 'crash-tested', 'attachment-type'],
  'pet-ramps': ['brand', 'length', 'weight-capacity', 'foldable', 'surface-type'],
  'pet-stairs': ['brand', 'steps', 'height', 'weight-capacity', 'foldable'],
  'outdoor-kennels': ['brand', 'size', 'material', 'roof-included', 'weatherproof'],
  'dog-runs': ['brand', 'size', 'height', 'material', 'roof-included'],
  'tie-out-stakes': ['brand', 'length', 'weight-capacity', 'swivel', 'material'],
  'tie-out-cables': ['brand', 'length', 'weight-capacity', 'coated', 'swivel'],
  'pet-tents': ['brand', 'size', 'material', 'foldable', 'mesh-windows'],
  'camping-gear': ['brand', 'type', 'size', 'weight-capacity', 'portable'],
  
  // Pet Cleanup & Odor Control
  'pet-cleanup-odor': ['brand', 'size', 'type', 'scent'],
  'stain-removers': ['brand', 'size', 'enzyme-based', 'scent', 'spray-pour'],
  'odor-eliminators': ['brand', 'size', 'scent', 'spray-granules', 'enzyme-based'],
  'carpet-cleaners': ['brand', 'size', 'machine-type', 'pet-formula'],
  'pet-wipes': ['brand', 'count', 'scent', 'hypoallergenic', 'purpose'],
  'litter-deodorizers': ['brand', 'size', 'scent', 'baking-soda', 'powder-spray'],
  'air-fresheners': ['brand', 'size', 'scent', 'type', 'pet-safe'],
  'pooper-scoopers': ['brand', 'type', 'material', 'handle-length', 'rake-included'],
  'waste-disposal': ['brand', 'type', 'capacity', 'odor-control', 'bags-included'],
  
  // Pet Furniture & Home
  'pet-furniture-home': ['brand', 'pet-type', 'size', 'material', 'color'],
  'pet-sofas': ['brand', 'size', 'material', 'weight-capacity', 'washable-cover'],
  'pet-chairs': ['brand', 'size', 'material', 'weight-capacity', 'elevated'],
  'pet-blankets': ['brand', 'size', 'material', 'washable', 'waterproof'],
  'furniture-covers': ['brand', 'size', 'material', 'waterproof', 'non-slip', 'reversible'],
  'pet-steps-furniture': ['brand', 'steps', 'height', 'weight-capacity', 'storage'],
  'feeding-stations': ['brand', 'bowls-included', 'elevated', 'storage', 'material'],
  'storage-containers': ['brand', 'capacity', 'material', 'airtight', 'wheels'],
  'treat-jars': ['brand', 'capacity', 'material', 'airtight', 'design'],
  
  // Pet Apparel & Accessories
  'pet-apparel-accessories': ['brand', 'pet-type', 'size', 'material', 'season'],
  'pet-costumes': ['brand', 'pet-type', 'size', 'theme', 'pieces'],
  'pet-bandanas': ['brand', 'size', 'material', 'pattern', 'adjustable'],
  'pet-bow-ties': ['brand', 'size', 'material', 'pattern', 'attachment-type'],
  'rain-coats': ['brand', 'size', 'material', 'waterproof', 'reflective', 'hood'],
  'winter-coats': ['brand', 'size', 'material', 'insulation', 'waterproof', 'reflective'],
  'sweaters': ['brand', 'size', 'material', 'pattern', 'turtleneck'],
  'pajamas': ['brand', 'size', 'material', 'pattern', 'feet-coverage'],
  'life-vests': ['brand', 'size', 'weight-range', 'handle', 'reflective', 'buoyancy'],
  'goggles': ['brand', 'size', 'uv-protection', 'adjustable', 'interchangeable-lenses'],
  'sunglasses': ['brand', 'size', 'uv-protection', 'strap', 'lens-color'],
  
  // Pet Training & Behavior
  'pet-training-behavior': ['brand', 'pet-type', 'type', 'purpose'],
  'training-treats': ['brand', 'pet-type', 'size', 'flavor', 'low-calorie', 'soft-crunchy'],
  'treat-pouches': ['brand', 'size', 'material', 'clip-type', 'pockets'],
  'training-clickers': ['brand', 'type', 'wrist-strap', 'volume', 'button-type'],
  'target-sticks': ['brand', 'length', 'extendable', 'wrist-strap'],
  'agility-equipment': ['brand', 'type', 'size', 'adjustable', 'portable'],
  'training-pads-reusable': ['brand', 'size', 'layers', 'washable', 'absorbency'],
  'pheromone-diffusers': ['brand', 'coverage', 'refills-included', 'duration'],
  'bark-collars': ['brand', 'type', 'levels', 'rechargeable', 'waterproof'],
  'shock-collars': ['brand', 'range', 'levels', 'rechargeable', 'waterproof', 'remote'],
  'citronella-collars': ['brand', 'refills-included', 'adjustable', 'automatic'],
  'pet-cameras': ['brand', 'resolution', 'night-vision', 'two-way-audio', 'treat-dispenser'],
  'treat-dispensers': ['brand', 'capacity', 'programmable', 'camera', 'app-controlled'],
  'puzzle-feeders': ['brand', 'pet-type', 'difficulty', 'material', 'dishwasher-safe'],
  'slow-feeders': ['brand', 'capacity', 'material', 'pattern', 'non-slip'],
  'snuffle-mats': ['brand', 'size', 'material', 'washable', 'difficulty'],
  'interactive-toys': ['brand', 'pet-type', 'type', 'battery-required', 'difficulty'],
};
