/**
 * Stationery & Office Category Attribute Mappings
 * 
 * Comprehensive mappings for office supplies and stationery
 */

export const stationeryOfficeMappings = {
  // Main Stationery & Office
  'stationery-office': ['brand', 'size', 'color', 'quantity', 'material'],
  'stationery': ['brand', 'size', 'color', 'quantity', 'paper-type'],
  'office-supplies': ['brand', 'size', 'color', 'quantity', 'type'],
  
  // Writing Instruments
  'writing-instruments': ['brand', 'type', 'color', 'quantity', 'ink-type'],
  'pens': ['brand', 'type', 'color', 'quantity', 'ink-type', 'point-size'],
  'ballpoint-pens': ['brand', 'color', 'quantity', 'point-size', 'retractable', 'refillable'],
  'gel-pens': ['brand', 'color', 'quantity', 'point-size', 'retractable', 'ink-type'],
  'rollerball-pens': ['brand', 'color', 'quantity', 'point-size', 'refillable'],
  'fountain-pens': ['brand', 'nib-size', 'material', 'refillable', 'converter-cartridge'],
  'markers': ['brand', 'type', 'colors', 'quantity', 'tip-type', 'permanent-washable'],
  'permanent-markers': ['brand', 'color', 'quantity', 'tip-type', 'chisel-bullet'],
  'dry-erase-markers': ['brand', 'color', 'quantity', 'tip-type', 'low-odor'],
  'highlighters': ['brand', 'colors', 'quantity', 'tip-type', 'chisel-bullet'],
  'pencils': ['brand', 'type', 'quantity', 'lead-grade', 'eraser-included'],
  'mechanical-pencils': ['brand', 'lead-size', 'quantity', 'grip-type', 'refillable'],
  'colored-pencils': ['brand', 'colors', 'quantity', 'oil-wax', 'blendable'],
  'crayons': ['brand', 'colors', 'quantity', 'washable', 'non-toxic'],
  'chalk': ['brand', 'colors', 'quantity', 'dustless', 'type'],
  'charcoal': ['brand', 'type', 'quantity', 'hardness', 'compressed-vine'],
  'paint-markers': ['brand', 'colors', 'quantity', 'tip-size', 'surface-type'],
  'calligraphy-pens': ['brand', 'nib-size', 'quantity', 'ink-included', 'cartridge-dip'],
  'brush-pens': ['brand', 'colors', 'quantity', 'tip-type', 'water-based'],
  'stylus-pens': ['brand', 'compatibility', 'tip-type', 'rechargeable', 'pressure-levels'],
  
  // Paper Products
  'paper-products': ['brand', 'size', 'quantity', 'weight', 'color'],
  'printer-paper': ['brand', 'size', 'sheets', 'weight', 'brightness', 'multipurpose-specialty'],
  'copy-paper': ['brand', 'size', 'sheets', 'weight', 'brightness', 'reams'],
  'cardstock': ['brand', 'size', 'sheets', 'weight', 'color', 'finish'],
  'construction-paper': ['brand', 'size', 'sheets', 'colors', 'weight'],
  'tissue-paper': ['brand', 'sheets', 'colors', 'size', 'bleeding-non-bleeding'],
  'tracing-paper': ['brand', 'size', 'sheets', 'weight', 'transparency'],
  'graph-paper': ['brand', 'size', 'sheets', 'grid-size', 'ruling'],
  'lined-paper': ['brand', 'size', 'sheets', 'ruling', 'margin', 'hole-punched'],
  'sticky-notes': ['brand', 'size', 'sheets', 'colors', 'adhesive-strength', 'shape'],
  'index-cards': ['brand', 'size', 'quantity', 'ruled-blank', 'color', 'weight'],
  'notecards': ['brand', 'size', 'quantity', 'envelopes-included', 'blank-printed'],
  'envelopes': ['brand', 'size', 'quantity', 'color', 'seal-type', 'window'],
  'labels': ['brand', 'size', 'quantity', 'shape', 'adhesive-type', 'printable'],
  'stickers': ['brand', 'quantity', 'size', 'design', 'removable-permanent'],
  
  // Notebooks & Journals
  'notebooks-journals': ['brand', 'size', 'pages', 'ruling', 'binding', 'cover-type'],
  'notebooks': ['brand', 'size', 'pages', 'ruling', 'binding', 'subject-count'],
  'spiral-notebooks': ['brand', 'size', 'pages', 'ruling', 'subjects', 'perforated'],
  'composition-notebooks': ['brand', 'size', 'pages', 'ruling', 'cover-design'],
  'journals': ['brand', 'size', 'pages', 'ruling', 'binding', 'hardcover-softcover'],
  'planners': ['brand', 'size', 'layout', 'dated-undated', 'binding', 'duration'],
  'calendars': ['brand', 'type', 'size', 'year', 'wall-desk', 'binding'],
  'sketchbooks': ['brand', 'size', 'pages', 'paper-weight', 'binding', 'spiral-hardbound'],
  'drawing-pads': ['brand', 'size', 'sheets', 'paper-weight', 'texture', 'binding'],
  'watercolor-pads': ['brand', 'size', 'sheets', 'paper-weight', 'texture', 'binding'],
  'memo-pads': ['brand', 'size', 'sheets', 'ruling', 'adhesive', 'perforated'],
  'legal-pads': ['brand', 'size', 'sheets', 'ruling', 'color', 'perforated'],
  'address-books': ['brand', 'size', 'pages', 'alphabetical', 'binding'],

  // Binders & Filing
  'binders-filing': ['brand', 'size', 'capacity', 'material', 'color'],
  'binders': ['brand', 'ring-size', 'capacity', 'material', 'color', 'd-ring-round-ring'],
  'sheet-protectors': ['brand', 'size', 'quantity', 'thickness', 'top-loading', 'hole-punched'],
  'dividers': ['brand', 'tabs', 'size', 'material', 'insertable-printed', 'color'],
  'folders': ['brand', 'size', 'quantity', 'material', 'color', 'pockets'],
  'file-folders': ['brand', 'size', 'quantity', 'tab-position', 'color', 'material'],
  'hanging-folders': ['brand', 'size', 'quantity', 'tab-position', 'color', 'box-bottom'],
  'pocket-folders': ['brand', 'size', 'quantity', 'pockets', 'material', 'color'],
  'expanding-folders': ['brand', 'size', 'pockets', 'closure-type', 'capacity'],
  'accordion-folders': ['brand', 'size', 'pockets', 'closure-type', 'capacity'],
  'file-boxes': ['brand', 'size', 'material', 'lid-type', 'capacity', 'stackable'],
  'magazine-holders': ['brand', 'size', 'material', 'color', 'quantity'],
  'document-holders': ['brand', 'size', 'material', 'orientation', 'wall-desk'],
  'clipboards': ['brand', 'size', 'material', 'storage', 'clip-type'],
  'portfolio-folders': ['brand', 'size', 'material', 'pockets', 'zipper', 'handle'],
  
  // Desk Accessories
  'desk-accessories': ['brand', 'size', 'material', 'color', 'type'],
  'desk-organizers': ['brand', 'size', 'material', 'compartments', 'drawer', 'color'],
  'pen-holders': ['brand', 'size', 'material', 'compartments', 'color'],
  'pencil-cups': ['brand', 'size', 'material', 'color', 'capacity'],
  'desk-trays': ['brand', 'size', 'material', 'tiers', 'stackable', 'color'],
  'letter-trays': ['brand', 'size', 'material', 'tiers', 'stackable', 'orientation'],
  'desk-pads': ['brand', 'size', 'material', 'calendar', 'refillable'],
  'mouse-pads': ['brand', 'size', 'material', 'wrist-rest', 'non-slip'],
  'monitor-stands': ['brand', 'size', 'material', 'height-adjustable', 'storage', 'weight-capacity'],
  'laptop-stands': ['brand', 'size', 'material', 'adjustable', 'portable', 'cooling'],
  'book-stands': ['brand', 'size', 'material', 'adjustable', 'page-holder'],
  'bookends': ['brand', 'size', 'material', 'weight', 'non-slip', 'pair'],
  'business-card-holders': ['brand', 'capacity', 'material', 'desk-wall', 'rotating'],
  'tape-dispensers': ['brand', 'size', 'material', 'weighted', 'tape-width'],
  'stapler-removers': ['brand', 'type', 'material', 'magnetic'],
  'paper-clip-holders': ['brand', 'size', 'material', 'magnetic', 'color'],
  'cable-organizers': ['brand', 'type', 'size', 'material', 'adhesive'],
  'desk-lamps': ['brand', 'type', 'brightness', 'adjustable', 'power-source', 'color-temperature'],

  // Office Equipment
  'office-equipment': ['brand', 'type', 'size', 'power-source', 'capacity'],
  'staplers': ['brand', 'capacity', 'staple-size', 'type', 'jam-free', 'desktop-handheld'],
  'staples': ['brand', 'size', 'quantity', 'standard-heavy-duty', 'chisel-point'],
  'hole-punches': ['brand', 'capacity', 'holes', 'adjustable', 'desktop-handheld'],
  'paper-cutters': ['brand', 'cutting-length', 'capacity', 'blade-type', 'safety-guard'],
  'trimmers': ['brand', 'cutting-length', 'capacity', 'blade-type', 'rotary-guillotine'],
  'laminators': ['brand', 'width', 'speed', 'temperature-settings', 'pouches-included'],
  'laminating-pouches': ['brand', 'size', 'quantity', 'thickness', 'thermal-self-seal'],
  'binding-machines': ['brand', 'binding-type', 'capacity', 'punch-capacity', 'electric-manual'],
  'binding-combs': ['brand', 'size', 'quantity', 'capacity', 'color'],
  'shredders': ['brand', 'cut-type', 'capacity', 'security-level', 'bin-size', 'jam-proof'],
  'label-makers': ['brand', 'type', 'tape-width', 'keyboard-touchscreen', 'battery-plug'],
  'label-tape': ['brand', 'width', 'length', 'color', 'compatibility', 'adhesive-type'],
  'calculators': ['brand', 'type', 'display-digits', 'functions', 'solar-battery', 'printing'],
  'time-clocks': ['brand', 'type', 'capacity', 'automatic-manual', 'cards-included'],
  'paper-shredders': ['brand', 'cut-type', 'capacity', 'security-level', 'bin-size'],
  'pencil-sharpeners': ['brand', 'type', 'size', 'electric-manual', 'auto-stop'],
  'erasers': ['brand', 'type', 'size', 'quantity', 'white-pink', 'kneaded'],
  'correction-fluid': ['brand', 'size', 'type', 'quick-dry', 'pen-bottle'],
  'correction-tape': ['brand', 'width', 'length', 'quantity', 'refillable'],
  
  // Tapes & Adhesives
  'tapes-adhesives': ['brand', 'type', 'size', 'quantity', 'adhesive-strength'],
  'scotch-tape': ['brand', 'width', 'length', 'quantity', 'matte-glossy', 'dispenser-included'],
  'masking-tape': ['brand', 'width', 'length', 'quantity', 'temperature-rating'],
  'duct-tape': ['brand', 'width', 'length', 'color', 'adhesive-strength', 'waterproof'],
  'packing-tape': ['brand', 'width', 'length', 'quantity', 'clear-tan', 'dispenser-included'],
  'double-sided-tape': ['brand', 'width', 'length', 'quantity', 'foam-flat', 'removable-permanent'],
  'washi-tape': ['brand', 'width', 'length', 'design', 'quantity', 'repositionable'],
  'electrical-tape': ['brand', 'width', 'length', 'color', 'temperature-rating', 'voltage-rating'],
  'glue-sticks': ['brand', 'size', 'quantity', 'washable', 'dries-clear', 'acid-free'],
  'liquid-glue': ['brand', 'size', 'type', 'washable', 'dries-clear', 'acid-free'],
  'super-glue': ['brand', 'size', 'quantity', 'gel-liquid', 'precision-tip'],
  'glue-guns': ['brand', 'wattage', 'temperature', 'stick-size', 'cordless', 'stand'],
  'glue-sticks-hot': ['brand', 'diameter', 'length', 'quantity', 'temperature', 'color'],
  'spray-adhesive': ['brand', 'size', 'type', 'repositionable-permanent', 'acid-free'],
  'mounting-tape': ['brand', 'width', 'length', 'weight-capacity', 'indoor-outdoor', 'removable'],

  // Clips & Fasteners
  'clips-fasteners': ['brand', 'type', 'size', 'quantity', 'material'],
  'paper-clips': ['brand', 'size', 'quantity', 'material', 'color', 'smooth-ridged'],
  'binder-clips': ['brand', 'size', 'quantity', 'capacity', 'color'],
  'bulldog-clips': ['brand', 'size', 'quantity', 'capacity', 'color'],
  'push-pins': ['brand', 'size', 'quantity', 'color', 'head-type'],
  'thumbtacks': ['brand', 'size', 'quantity', 'color', 'head-type'],
  'rubber-bands': ['brand', 'size', 'quantity', 'weight', 'color'],
  'brads': ['brand', 'size', 'quantity', 'material', 'color'],
  'fasteners': ['brand', 'type', 'size', 'quantity', 'material'],
  
  // Mailing & Shipping
  'mailing-shipping': ['brand', 'size', 'quantity', 'type', 'material'],
  'shipping-boxes': ['brand', 'size', 'quantity', 'material', 'strength', 'flat-assembled'],
  'bubble-mailers': ['brand', 'size', 'quantity', 'self-seal', 'bubble-size'],
  'padded-envelopes': ['brand', 'size', 'quantity', 'self-seal', 'padding-type'],
  'poly-mailers': ['brand', 'size', 'quantity', 'self-seal', 'waterproof', 'color'],
  'bubble-wrap': ['brand', 'width', 'length', 'bubble-size', 'perforated'],
  'packing-peanuts': ['brand', 'volume', 'material', 'biodegradable', 'anti-static'],
  'packing-paper': ['brand', 'sheets', 'size', 'weight', 'newsprint-kraft'],
  'stretch-wrap': ['brand', 'width', 'length', 'thickness', 'handle-included'],
  'shipping-labels': ['brand', 'size', 'quantity', 'adhesive-type', 'printer-compatible'],
  'postage-scales': ['brand', 'capacity', 'accuracy', 'digital-mechanical', 'battery-plug'],
  'letter-openers': ['brand', 'type', 'material', 'safety', 'electric-manual'],
  'mail-sorters': ['brand', 'compartments', 'material', 'size', 'wall-desk'],
  
  // Art Supplies
  'art-supplies': ['brand', 'type', 'quantity', 'material', 'age-group'],
  'paints': ['brand', 'type', 'colors', 'size', 'water-oil-acrylic', 'tubes-bottles'],
  'paintbrushes': ['brand', 'size', 'quantity', 'bristle-type', 'shape', 'synthetic-natural'],
  'canvases': ['brand', 'size', 'quantity', 'stretched-panel', 'primed', 'depth'],
  'easels': ['brand', 'type', 'height', 'material', 'adjustable', 'tabletop-floor'],
  'palettes': ['brand', 'size', 'material', 'wells', 'disposable-reusable'],
  'pastels': ['brand', 'type', 'colors', 'quantity', 'oil-soft-hard'],
  'ink': ['brand', 'color', 'size', 'type', 'waterproof', 'archival'],
  'craft-paper': ['brand', 'size', 'sheets', 'colors', 'weight', 'type'],
  'scissors': ['brand', 'size', 'blade-type', 'handle-type', 'left-right-handed'],
  'craft-knives': ['brand', 'blade-size', 'handle-type', 'retractable', 'blades-included'],
  'cutting-mats': ['brand', 'size', 'grid', 'self-healing', 'double-sided'],
  'rulers': ['brand', 'length', 'material', 'units', 'cork-backed', 'flexible-rigid'],
  'protractors': ['brand', 'size', 'material', 'full-half-circle', 'units'],
  'compasses': ['brand', 'type', 'material', 'adjustable', 'pencil-included'],
  'templates': ['brand', 'type', 'size', 'material', 'shapes-letters'],

  // Office Furniture
  'office-furniture': ['brand', 'size', 'material', 'color', 'assembly-required'],
  'office-chairs': ['brand', 'type', 'material', 'adjustable', 'weight-capacity', 'lumbar-support'],
  'desk-chairs': ['brand', 'material', 'adjustable-height', 'armrests', 'swivel', 'weight-capacity'],
  'executive-chairs': ['brand', 'material', 'adjustable', 'lumbar-support', 'headrest', 'weight-capacity'],
  'task-chairs': ['brand', 'material', 'adjustable-height', 'armrests', 'swivel', 'weight-capacity'],
  'ergonomic-chairs': ['brand', 'material', 'adjustments', 'lumbar-support', 'headrest', 'weight-capacity'],
  'guest-chairs': ['brand', 'material', 'armrests', 'stackable', 'weight-capacity'],
  'desks': ['brand', 'size', 'material', 'drawers', 'keyboard-tray', 'cable-management'],
  'computer-desks': ['brand', 'size', 'material', 'keyboard-tray', 'monitor-shelf', 'cable-management'],
  'standing-desks': ['brand', 'size', 'material', 'adjustable-height', 'electric-manual', 'memory-presets'],
  'l-shaped-desks': ['brand', 'size', 'material', 'drawers', 'keyboard-tray', 'reversible'],
  'writing-desks': ['brand', 'size', 'material', 'drawers', 'style'],
  'filing-cabinets': ['brand', 'drawers', 'size', 'material', 'locking', 'vertical-lateral'],
  'bookcases': ['brand', 'shelves', 'size', 'material', 'adjustable-shelves', 'backing'],
  'storage-cabinets': ['brand', 'size', 'material', 'shelves', 'doors', 'locking'],
  'credenzas': ['brand', 'size', 'material', 'storage', 'drawers', 'doors'],
  'conference-tables': ['brand', 'size', 'shape', 'material', 'seating-capacity', 'cable-management'],
  'reception-desks': ['brand', 'size', 'material', 'storage', 'transaction-counter'],
  'office-partitions': ['brand', 'height', 'width', 'material', 'freestanding-mounted', 'fabric-glass'],
  'coat-racks': ['brand', 'height', 'material', 'hooks', 'freestanding-wall', 'umbrella-holder'],
  'footrests': ['brand', 'size', 'material', 'adjustable', 'massage', 'non-slip'],
  
  // Presentation Supplies
  'presentation-supplies': ['brand', 'size', 'type', 'quantity'],
  'whiteboards': ['brand', 'size', 'material', 'magnetic', 'frame', 'mounting-type'],
  'bulletin-boards': ['brand', 'size', 'material', 'frame', 'mounting-type', 'fabric-cork'],
  'easel-pads': ['brand', 'size', 'sheets', 'ruling', 'perforated', 'adhesive'],
  'chart-paper': ['brand', 'size', 'sheets', 'ruling', 'color'],
  'poster-boards': ['brand', 'size', 'quantity', 'color', 'weight', 'finish'],
  'display-boards': ['brand', 'size', 'panels', 'material', 'foldable', 'self-standing'],
  'name-badges': ['brand', 'size', 'quantity', 'type', 'clip-pin-magnetic', 'inserts-included'],
  'lanyards': ['brand', 'length', 'width', 'material', 'attachment-type', 'quantity'],
  'badge-holders': ['brand', 'size', 'quantity', 'orientation', 'attachment-type', 'clear-color'],
  'pointers': ['brand', 'length', 'type', 'laser-telescoping', 'battery-required'],
  'projector-screens': ['brand', 'size', 'aspect-ratio', 'material', 'manual-electric', 'mounting-type'],
  
  // Storage & Organization
  'storage-organization': ['brand', 'size', 'material', 'capacity', 'type'],
  'storage-boxes': ['brand', 'size', 'material', 'lid-type', 'stackable', 'quantity'],
  'plastic-bins': ['brand', 'size', 'capacity', 'lid-included', 'stackable', 'clear-colored'],
  'drawer-organizers': ['brand', 'size', 'compartments', 'material', 'expandable'],
  'desktop-organizers': ['brand', 'size', 'material', 'compartments', 'drawer', 'rotating'],
  'wall-organizers': ['brand', 'size', 'material', 'pockets-slots', 'mounting-type'],
  'rolling-carts': ['brand', 'tiers', 'size', 'material', 'weight-capacity', 'locking-wheels'],
  'utility-carts': ['brand', 'tiers', 'size', 'material', 'weight-capacity', 'handle'],
  'shelving-units': ['brand', 'shelves', 'size', 'material', 'weight-capacity', 'adjustable'],
  'wire-shelving': ['brand', 'shelves', 'size', 'weight-capacity', 'adjustable', 'wheels'],
  'cube-storage': ['brand', 'cubes', 'size', 'material', 'bins-included', 'stackable'],
  'magazine-files': ['brand', 'size', 'material', 'color', 'quantity'],
  'sorters': ['brand', 'compartments', 'size', 'material', 'vertical-horizontal'],
};
