/**
 * Toys & Baby Category Attribute Mappings
 * 
 * Comprehensive mappings for toys, baby products, and children's items
 */

export const toysBabyMappings = {
  // Main Toys & Baby
  'toys-baby': ['brand', 'age-group', 'color', 'material', 'safety-certified'],
  'toys': ['brand', 'age-group', 'color', 'material', 'educational', 'battery-required'],
  'baby-products': ['brand', 'age-group', 'color', 'material', 'safety-certified'],
  
  // Action Figures & Dolls
  'action-figures': ['brand', 'character', 'height', 'articulation', 'accessories-included'],
  'dolls': ['brand', 'height', 'age-group', 'hair-color', 'accessories-included', 'interactive'],
  'doll-houses': ['brand', 'size', 'rooms', 'furniture-included', 'material', 'assembly-required'],
  'doll-accessories': ['brand', 'type', 'compatibility', 'pieces'],
  'collectible-figures': ['brand', 'character', 'series', 'height', 'limited-edition'],
  'plush-toys': ['brand', 'character', 'size', 'material', 'washable', 'age-group'],
  'stuffed-animals': ['brand', 'animal-type', 'size', 'material', 'washable'],
  
  // Building & Construction
  'building-toys': ['brand', 'pieces', 'age-group', 'theme', 'compatible-with'],
  'building-blocks': ['brand', 'pieces', 'age-group', 'material', 'theme', 'storage-included'],
  'lego-sets': ['brand', 'pieces', 'age-group', 'theme', 'minifigures'],
  'magnetic-tiles': ['brand', 'pieces', 'age-group', 'shapes', 'storage-included'],
  'construction-sets': ['brand', 'pieces', 'age-group', 'theme', 'motorized'],
  'model-kits': ['brand', 'scale', 'pieces', 'age-group', 'theme', 'paint-required'],
  
  // Educational Toys
  'educational-toys': ['brand', 'age-group', 'subject', 'skill-development', 'interactive'],
  'stem-toys': ['brand', 'age-group', 'subject', 'pieces', 'battery-required'],
  'science-kits': ['brand', 'age-group', 'experiments', 'subject', 'supervision-required'],
  'robotics-kits': ['brand', 'age-group', 'pieces', 'programmable', 'app-controlled'],
  'coding-toys': ['brand', 'age-group', 'platform', 'screen-free', 'app-required'],
  'learning-tablets': ['brand', 'age-group', 'screen-size', 'apps-included', 'parental-controls'],
  'electronic-learning': ['brand', 'age-group', 'subject', 'interactive', 'battery-required'],
  'flash-cards': ['brand', 'age-group', 'subject', 'quantity', 'double-sided'],
  'puzzles': ['brand', 'pieces', 'age-group', 'theme', 'size'],
  'jigsaw-puzzles': ['brand', 'pieces', 'age-group', 'size', 'theme'],
  '3d-puzzles': ['brand', 'pieces', 'age-group', 'theme', 'size'],
  'brain-teasers': ['brand', 'age-group', 'difficulty', 'type'],
  
  // Arts & Crafts
  'arts-crafts': ['brand', 'age-group', 'type', 'pieces', 'washable'],
  'coloring-books': ['brand', 'age-group', 'pages', 'theme', 'size'],
  'crayons': ['brand', 'quantity', 'washable', 'non-toxic', 'age-group'],
  'markers': ['brand', 'quantity', 'washable', 'tip-type', 'colors'],
  'colored-pencils': ['brand', 'quantity', 'age-group', 'sharpener-included'],
  'paint-sets': ['brand', 'type', 'colors', 'brushes-included', 'age-group'],
  'craft-kits': ['brand', 'age-group', 'type', 'pieces', 'instructions-included'],
  'modeling-clay': ['brand', 'weight', 'colors', 'non-toxic', 'air-dry'],
  'play-dough': ['brand', 'weight', 'colors', 'non-toxic', 'tools-included'],
  'bead-kits': ['brand', 'pieces', 'age-group', 'type', 'storage-included'],
  'sewing-kits': ['brand', 'age-group', 'projects', 'pieces', 'instructions'],
  'origami-kits': ['brand', 'sheets', 'age-group', 'patterns', 'instructions'],
  
  // Outdoor & Sports Toys
  'outdoor-toys': ['brand', 'age-group', 'material', 'weather-resistant'],
  'ride-on-toys': ['brand', 'age-group', 'weight-capacity', 'powered', 'speed'],
  'electric-cars': ['brand', 'age-group', 'weight-capacity', 'speed', 'battery-life', 'remote-control'],
  'scooters': ['brand', 'age-group', 'weight-capacity', 'wheels', 'foldable', 'adjustable-height'],
  'skateboards': ['brand', 'age-group', 'deck-size', 'weight-capacity', 'wheel-size'],
  'bicycles': ['brand', 'age-group', 'wheel-size', 'gears', 'training-wheels'],
  'tricycles': ['brand', 'age-group', 'weight-capacity', 'adjustable', 'storage'],
  'balance-bikes': ['brand', 'age-group', 'weight-capacity', 'adjustable-seat', 'wheel-size'],
  'trampolines': ['brand', 'diameter', 'weight-capacity', 'safety-net', 'springs'],
  'swing-sets': ['brand', 'swings', 'weight-capacity', 'material', 'slide-included'],
  'playhouses': ['brand', 'size', 'material', 'indoor-outdoor', 'assembly-required'],
  'sandboxes': ['brand', 'size', 'cover-included', 'seats', 'material'],
  'water-tables': ['brand', 'age-group', 'accessories-included', 'drain-plug'],
  'splash-pads': ['brand', 'size', 'sprinklers', 'material', 'hose-connection'],
  'kiddie-pools': ['brand', 'size', 'capacity', 'inflatable-rigid', 'drain-plug'],
  'water-guns': ['brand', 'age-group', 'capacity', 'range', 'pump-type'],
  'bubble-machines': ['brand', 'age-group', 'bubble-solution-included', 'battery-required'],
  'kites': ['brand', 'age-group', 'size', 'type', 'string-included'],
  'sports-equipment': ['brand', 'age-group', 'sport-type', 'size'],
  
  // Remote Control & Vehicles
  'remote-control-toys': ['brand', 'age-group', 'type', 'range', 'battery-required'],
  'rc-cars': ['brand', 'age-group', 'scale', 'speed', 'terrain', 'battery-life'],
  'rc-trucks': ['brand', 'age-group', 'scale', 'terrain', 'battery-life'],
  'rc-drones': ['brand', 'age-group', 'camera', 'flight-time', 'range', 'gps'],
  'rc-helicopters': ['brand', 'age-group', 'channels', 'flight-time', 'indoor-outdoor'],
  'rc-boats': ['brand', 'age-group', 'speed', 'battery-life', 'waterproof'],
  'die-cast-cars': ['brand', 'scale', 'material', 'opening-parts', 'age-group'],
  'toy-trains': ['brand', 'age-group', 'pieces', 'battery-required', 'track-included'],
  'train-sets': ['brand', 'age-group', 'pieces', 'track-length', 'battery-required'],
  'slot-cars': ['brand', 'scale', 'track-length', 'cars-included', 'age-group'],
  
  // Games & Puzzles
  'board-games': ['brand', 'age-group', 'players', 'playtime', 'category'],
  'card-games': ['brand', 'age-group', 'players', 'cards', 'category'],
  'party-games': ['brand', 'age-group', 'players', 'playtime'],
  'strategy-games': ['brand', 'age-group', 'players', 'playtime', 'complexity'],
  'trivia-games': ['brand', 'age-group', 'players', 'categories', 'questions'],
  'dice-games': ['brand', 'age-group', 'players', 'dice-included'],
  'memory-games': ['brand', 'age-group', 'pieces', 'theme'],
  'matching-games': ['brand', 'age-group', 'pieces', 'theme'],
  
  // Pretend Play
  'pretend-play': ['brand', 'age-group', 'theme', 'pieces', 'interactive'],
  'play-kitchens': ['brand', 'age-group', 'size', 'accessories-included', 'interactive'],
  'play-food': ['brand', 'age-group', 'pieces', 'material', 'theme'],
  'tea-sets': ['brand', 'age-group', 'pieces', 'material'],
  'tool-sets': ['brand', 'age-group', 'pieces', 'material', 'storage-included'],
  'doctor-kits': ['brand', 'age-group', 'pieces', 'case-included'],
  'dress-up': ['brand', 'age-group', 'character', 'size', 'accessories-included'],
  'costumes': ['brand', 'age-group', 'character', 'size', 'pieces'],
  'play-tents': ['brand', 'age-group', 'size', 'theme', 'tunnel-included'],
  'puppet-theaters': ['brand', 'age-group', 'size', 'puppets-included'],
  'puppets': ['brand', 'age-group', 'type', 'character', 'material'],
  'cash-registers': ['brand', 'age-group', 'interactive', 'accessories-included', 'battery-required'],
  'shopping-carts': ['brand', 'age-group', 'size', 'material', 'accessories-included'],
  
  // Musical Toys
  'musical-toys': ['brand', 'age-group', 'instrument-type', 'battery-required'],
  'toy-instruments': ['brand', 'age-group', 'type', 'material', 'tuned'],
  'toy-pianos': ['brand', 'age-group', 'keys', 'songs-included', 'battery-required'],
  'toy-guitars': ['brand', 'age-group', 'strings', 'size', 'tunable'],
  'toy-drums': ['brand', 'age-group', 'pieces', 'sticks-included'],
  'music-boxes': ['brand', 'age-group', 'song', 'wind-up-battery'],
  'karaoke-machines': ['brand', 'age-group', 'microphones', 'songs-included', 'recording'],
  
  // Electronic Toys
  'electronic-toys': ['brand', 'age-group', 'battery-required', 'interactive'],
  'interactive-pets': ['brand', 'age-group', 'animal-type', 'features', 'battery-required'],
  'robotic-toys': ['brand', 'age-group', 'programmable', 'app-controlled', 'battery-required'],
  'talking-toys': ['brand', 'age-group', 'phrases', 'interactive', 'battery-required'],
  'electronic-games': ['brand', 'age-group', 'games-included', 'screen-type', 'battery-required'],
  'handheld-games': ['brand', 'age-group', 'games-included', 'screen-size', 'battery-required'],
  'video-game-consoles': ['brand', 'age-group', 'games-included', 'controllers', 'educational'],
  
  // Baby Gear
  'baby-gear': ['brand', 'age-group', 'weight-capacity', 'safety-certified'],
  'strollers': ['brand', 'type', 'weight-capacity', 'foldable', 'storage', 'canopy'],
  'car-seats': ['brand', 'age-group', 'weight-range', 'isofix', 'recline-positions', 'safety-rating'],
  'infant-car-seats': ['brand', 'weight-range', 'base-included', 'canopy', 'safety-rating'],
  'convertible-car-seats': ['brand', 'weight-range', 'positions', 'recline', 'safety-rating'],
  'booster-seats': ['brand', 'weight-range', 'high-back-backless', 'cup-holders'],
  'baby-carriers': ['brand', 'weight-capacity', 'positions', 'material', 'adjustable'],
  'baby-wraps': ['brand', 'length', 'material', 'stretchy-woven', 'washable'],
  'baby-slings': ['brand', 'weight-capacity', 'material', 'adjustable', 'rings'],
  'high-chairs': ['brand', 'age-group', 'weight-capacity', 'adjustable-height', 'tray-included', 'foldable'],
  'booster-seats-feeding': ['brand', 'age-group', 'weight-capacity', 'tray-included', 'portable'],
  'play-yards': ['brand', 'size', 'weight-capacity', 'bassinet-included', 'changing-table'],
  'playpens': ['brand', 'size', 'weight-capacity', 'portable', 'mesh-sides'],
  'baby-gates': ['brand', 'width-range', 'height', 'pressure-hardware', 'walk-through'],
  'baby-swings': ['brand', 'age-group', 'weight-capacity', 'speeds', 'music', 'battery-plug'],
  'bouncers': ['brand', 'age-group', 'weight-capacity', 'vibration', 'music', 'foldable'],
  'rockers': ['brand', 'age-group', 'weight-capacity', 'recline', 'music', 'portable'],
  'jumpers': ['brand', 'age-group', 'weight-capacity', 'doorway-stationary', 'toys-included'],
  'activity-centers': ['brand', 'age-group', 'weight-capacity', 'toys-included', 'adjustable-height'],
  'walkers': ['brand', 'age-group', 'weight-capacity', 'adjustable-height', 'toys-included', 'foldable'],
  'push-toys': ['brand', 'age-group', 'weight-capacity', 'adjustable-handle', 'storage'],
  
  // Nursery Furniture
  'nursery-furniture': ['brand', 'material', 'color', 'assembly-required', 'safety-certified'],
  'cribs': ['brand', 'type', 'mattress-size', 'convertible', 'adjustable-height', 'material'],
  'bassinets': ['brand', 'weight-capacity', 'portable', 'storage', 'canopy'],
  'cradles': ['brand', 'weight-capacity', 'rocking-stationary', 'material', 'mattress-included'],
  'changing-tables': ['brand', 'weight-capacity', 'storage', 'safety-strap', 'pad-included'],
  'dressers': ['brand', 'drawers', 'material', 'changing-top', 'anti-tip'],
  'gliders': ['brand', 'weight-capacity', 'reclining', 'ottoman-included', 'material'],
  'rocking-chairs': ['brand', 'weight-capacity', 'material', 'cushioned', 'armrests'],
  'toy-storage': ['brand', 'capacity', 'bins-included', 'material', 'size'],
  'bookshelf': ['brand', 'shelves', 'material', 'size', 'anti-tip'],
  
  // Baby Bedding
  'baby-bedding': ['brand', 'size', 'material', 'pieces', 'washable'],
  'crib-sheets': ['brand', 'size', 'material', 'fitted', 'pack-size'],
  'crib-mattresses': ['brand', 'size', 'firmness', 'waterproof', 'dual-sided'],
  'mattress-protectors': ['brand', 'size', 'waterproof', 'breathable', 'fitted'],
  'crib-bumpers': ['brand', 'size', 'material', 'breathable', 'ties'],
  'baby-blankets': ['brand', 'size', 'material', 'weight', 'washable'],
  'swaddles': ['brand', 'size', 'material', 'closure-type', 'pack-size'],
  'sleep-sacks': ['brand', 'size', 'tog-rating', 'material', 'zipper-type'],
  'nursing-pillows': ['brand', 'shape', 'material', 'washable-cover', 'adjustable'],
  
  // Feeding
  'baby-feeding': ['brand', 'age-group', 'material', 'bpa-free'],
  'baby-bottles': ['brand', 'capacity', 'material', 'nipple-flow', 'anti-colic', 'pack-size'],
  'bottle-nipples': ['brand', 'flow-rate', 'material', 'compatibility', 'pack-size'],
  'sippy-cups': ['brand', 'capacity', 'material', 'spill-proof', 'handles', 'bpa-free'],
  'training-cups': ['brand', 'capacity', 'material', 'handles', 'spout-type', 'bpa-free'],
  'baby-bowls': ['brand', 'material', 'suction-base', 'microwave-safe', 'pack-size'],
  'baby-plates': ['brand', 'material', 'sections', 'suction-base', 'pack-size'],
  'baby-spoons': ['brand', 'material', 'soft-tip', 'temperature-sensing', 'pack-size'],
  'baby-forks': ['brand', 'material', 'rounded-tips', 'pack-size'],
  'bibs': ['brand', 'material', 'waterproof', 'pocket', 'closure-type', 'pack-size'],
  'placemats': ['brand', 'material', 'suction', 'sections', 'dishwasher-safe'],
  'bottle-warmers': ['brand', 'type', 'speed', 'auto-shutoff', 'compatibility'],
  'bottle-sterilizers': ['brand', 'capacity', 'type', 'cycle-time', 'auto-shutoff'],
  'bottle-brushes': ['brand', 'material', 'nipple-brush', 'stand-included'],
  'drying-racks': ['brand', 'capacity', 'material', 'drip-tray', 'foldable'],
  'breast-pumps': ['brand', 'type', 'suction-levels', 'battery-electric', 'double-single'],
  'nursing-covers': ['brand', 'material', 'size', 'wire-frame', 'storage-pocket'],
  'formula-dispensers': ['brand', 'compartments', 'material', 'pour-spout', 'stackable'],
  
  // Diapering
  'diapering': ['brand', 'size', 'count', 'material'],
  'diapers': ['brand', 'size', 'count', 'absorbency', 'wetness-indicator'],
  'disposable-diapers': ['brand', 'size', 'count', 'absorbency', 'wetness-indicator', 'hypoallergenic'],
  'cloth-diapers': ['brand', 'size', 'material', 'closure-type', 'inserts-included'],
  'diaper-inserts': ['brand', 'size', 'material', 'absorbency', 'pack-size'],
  'swim-diapers': ['brand', 'size', 'reusable-disposable', 'pack-size'],
  'training-pants': ['brand', 'size', 'count', 'gender', 'pull-up'],
  'wipes': ['brand', 'count', 'scented-unscented', 'hypoallergenic', 'dispenser-type'],
  'diaper-bags': ['brand', 'size', 'compartments', 'changing-pad', 'stroller-straps', 'insulated-pockets'],
  'diaper-pails': ['brand', 'capacity', 'odor-control', 'refill-type', 'foot-pedal'],
  'changing-pads': ['brand', 'size', 'material', 'waterproof', 'contoured', 'safety-strap'],
  'diaper-cream': ['brand', 'size', 'ingredients', 'zinc-oxide', 'fragrance-free'],
  
  // Bath Time
  'baby-bath': ['brand', 'age-group', 'material', 'size'],
  'baby-bathtubs': ['brand', 'age-group', 'size', 'drain-plug', 'temperature-indicator', 'foldable'],
  'bath-seats': ['brand', 'age-group', 'weight-capacity', 'suction-cups', 'recline'],
  'bath-toys': ['brand', 'age-group', 'material', 'floating', 'squirting', 'mold-resistant'],
  'hooded-towels': ['brand', 'size', 'material', 'absorbency', 'design'],
  'washcloths': ['brand', 'size', 'material', 'pack-size', 'soft'],
  'baby-shampoo': ['brand', 'size', 'tear-free', 'hypoallergenic', 'scent'],
  'baby-wash': ['brand', 'size', 'tear-free', 'hypoallergenic', 'moisturizing'],
  'baby-lotion': ['brand', 'size', 'hypoallergenic', 'fragrance-free', 'moisturizing'],
  'baby-oil': ['brand', 'size', 'mineral-plant', 'hypoallergenic', 'fragrance'],
  'baby-powder': ['brand', 'size', 'talc-free', 'cornstarch', 'fragrance'],
  'bath-thermometers': ['brand', 'type', 'digital-analog', 'floating', 'alarm'],
  
  // Health & Safety
  'baby-health-safety': ['brand', 'type', 'age-group'],
  'thermometers': ['brand', 'type', 'age-group', 'speed', 'memory'],
  'nasal-aspirators': ['brand', 'type', 'age-group', 'electric-manual', 'filters'],
  'medicine-dispensers': ['brand', 'type', 'measurement', 'pacifier-syringe'],
  'humidifiers': ['brand', 'capacity', 'runtime', 'cool-warm-mist', 'filter-type', 'night-light'],
  'baby-monitors': ['brand', 'type', 'range', 'video', 'two-way-audio', 'night-vision'],
  'video-monitors': ['brand', 'screen-size', 'range', 'night-vision', 'pan-tilt-zoom', 'two-way-audio'],
  'audio-monitors': ['brand', 'range', 'two-way-audio', 'rechargeable', 'sound-lights'],
  'movement-monitors': ['brand', 'type', 'sensitivity', 'alarm', 'battery-plug'],
  'outlet-covers': ['brand', 'quantity', 'type', 'removal-tool'],
  'corner-guards': ['brand', 'quantity', 'material', 'adhesive-type', 'color'],
  'cabinet-locks': ['brand', 'quantity', 'type', 'adhesive-drill', 'child-proof'],
  'door-stoppers': ['brand', 'quantity', 'type', 'material'],
  'toilet-locks': ['brand', 'type', 'adhesive-type', 'easy-adult-use'],
  'appliance-locks': ['brand', 'type', 'adhesive-type', 'adjustable'],
  'furniture-straps': ['brand', 'quantity', 'weight-capacity', 'mounting-type'],
  'night-lights': ['brand', 'type', 'brightness', 'color-changing', 'plug-battery', 'auto-sensor'],
  'sound-machines': ['brand', 'sounds', 'timer', 'volume-control', 'night-light', 'portable'],
  
  // Teething & Pacifiers
  'teething-pacifiers': ['brand', 'age-group', 'material', 'bpa-free'],
  'teethers': ['brand', 'age-group', 'material', 'refrigerate', 'texture'],
  'teething-toys': ['brand', 'age-group', 'material', 'refrigerate', 'rattle'],
  'pacifiers': ['brand', 'age-group', 'nipple-shape', 'material', 'orthodontic', 'pack-size'],
  'pacifier-clips': ['brand', 'length', 'material', 'clip-type', 'design'],
  'teething-gel': ['brand', 'size', 'natural', 'benzocaine-free', 'age-group'],
  
  // Baby Toys
  'baby-toys': ['brand', 'age-group', 'material', 'developmental-skill', 'battery-required'],
  'rattles': ['brand', 'age-group', 'material', 'sound-type', 'teether'],
  'soft-toys': ['brand', 'age-group', 'material', 'washable', 'size'],
  'activity-gyms': ['brand', 'age-group', 'toys-included', 'music', 'lights', 'mat-size'],
  'play-mats': ['brand', 'age-group', 'size', 'thickness', 'foldable', 'toys-included'],
  'stacking-toys': ['brand', 'age-group', 'pieces', 'material', 'nesting'],
  'sorting-toys': ['brand', 'age-group', 'pieces', 'shapes', 'colors'],
  'shape-sorters': ['brand', 'age-group', 'shapes', 'material', 'storage'],
  'musical-toys-baby': ['brand', 'age-group', 'sounds', 'lights', 'battery-required'],
  'bath-books': ['brand', 'age-group', 'pages', 'waterproof', 'squeaky'],
  'cloth-books': ['brand', 'age-group', 'pages', 'washable', 'crinkle', 'teether'],
  'board-books': ['brand', 'age-group', 'pages', 'theme', 'size'],
  'mobiles': ['brand', 'age-group', 'music', 'lights', 'remote-control', 'projection'],
  'crib-toys': ['brand', 'age-group', 'attachment-type', 'music', 'lights'],
  
  // Potty Training
  'potty-training': ['brand', 'age-group', 'type', 'capacity'],
  'potty-chairs': ['brand', 'age-group', 'removable-bowl', 'splash-guard', 'handles'],
  'potty-seats': ['brand', 'age-group', 'cushioned', 'handles', 'splash-guard', 'foldable'],
  'step-stools': ['brand', 'weight-capacity', 'height', 'non-slip', 'foldable'],
  'training-pants-potty': ['brand', 'size', 'gender', 'reusable-disposable', 'pack-size'],
  'potty-books': ['brand', 'age-group', 'pages', 'theme'],
  
  // Baby Clothing Accessories
  'baby-accessories': ['brand', 'age-group', 'material', 'size'],
  'baby-hats': ['brand', 'age-group', 'size', 'material', 'season', 'chin-strap'],
  'baby-mittens': ['brand', 'age-group', 'material', 'scratch-protection', 'pack-size'],
  'baby-socks': ['brand', 'age-group', 'size', 'material', 'non-slip', 'pack-size'],
  'baby-booties': ['brand', 'age-group', 'size', 'material', 'soft-sole'],
  'baby-sunglasses': ['brand', 'age-group', 'uv-protection', 'strap', 'flexible'],
  'sun-hats': ['brand', 'age-group', 'size', 'upf-rating', 'chin-strap', 'neck-flap'],
};
