<?php
/**
 * Script to create the attributes-data.php file for the plugin
 * 
 * This extracts the attributes array from bulk-create-attributes.php
 * and creates a separate file for the plugin to use
 */

$source_file = __DIR__ . '/../bulk-create-attributes.php';
$output_file = __DIR__ . '/../attributes-data.php';

// Read the source file
$content = file_get_contents($source_file);

// Extract the attributes array
preg_match('/\$attributes_to_create\s*=\s*array\((.*?)\);/s', $content, $matches);

if (empty($matches[1])) {
    die("Could not find attributes array in source file\n");
}

$attributes_array_content = $matches[1];

// Create the output file
$output = "<?php\n";
$output .= "/**\n";
$output .= " * Attributes Data for Bulk Attributes Creator Plugin\n";
$output .= " * \n";
$output .= " * This file contains all attributes to be created.\n";
$output .= " * Auto-generated from bulk-create-attributes.php\n";
$output .= " * \n";
$output .= " * DO NOT EDIT THIS FILE MANUALLY\n";
$output .= " * Regenerate using: php scripts/create-attributes-plugin.php\n";
$output .= " */\n\n";
$output .= "\$attributes_array = array(\n";
$output .= $attributes_array_content;
$output .= "\n);\n";

file_put_contents($output_file, $output);

echo "✅ Created attributes-data.php\n";
echo "📊 File size: " . number_format(filesize($output_file) / 1024, 2) . " KB\n";





